<?php


/**
 * This class adds structure of 'sf_blog_post' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Apr 22 19:56:25 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfBlogsPlugin.lib.model.map
 */
class sfBlogPostMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfBlogsPlugin.lib.model.map.sfBlogPostMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(sfBlogPostPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(sfBlogPostPeer::TABLE_NAME);
		$tMap->setPhpName('sfBlogPost');
		$tMap->setClassname('sfBlogPost');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('SF_BLOG_ID', 'SfBlogId', 'INTEGER', 'sf_blog', 'ID', false, null);

		$tMap->addForeignKey('AUTHOR_ID', 'AuthorId', 'INTEGER', 'sf_guard_user', 'ID', false, null);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', false, 255);

		$tMap->addColumn('STRIPPED_TITLE', 'StrippedTitle', 'VARCHAR', false, 255);

		$tMap->addColumn('EXTRACT', 'Extract', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CONTENT', 'Content', 'LONGVARCHAR', false, null);

		$tMap->addColumn('IS_PUBLISHED', 'IsPublished', 'BOOLEAN', false, null);

		$tMap->addColumn('ALLOW_COMMENTS', 'AllowComments', 'BOOLEAN', false, null);

		$tMap->addColumn('NB_COMMENTS', 'NbComments', 'INTEGER', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('PUBLISHED_AT', 'PublishedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // sfBlogPostMapBuilder
