<?php


/**
 * This class adds structure of 'sf_webpanel_bugs' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Apr 22 19:56:26 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfBugsPlugin.lib.model.map
 */
class SfWebpanelBugsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfBugsPlugin.lib.model.map.SfWebpanelBugsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(SfWebpanelBugsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(SfWebpanelBugsPeer::TABLE_NAME);
		$tMap->setPhpName('SfWebpanelBugs');
		$tMap->setClassname('SfWebpanelBugs');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', false, 50);

		$tMap->addColumn('MODULE_NAME', 'ModuleName', 'VARCHAR', false, 150);

		$tMap->addColumn('ACTION_NAME', 'ActionName', 'VARCHAR', false, 150);

		$tMap->addColumn('APP_NAME', 'AppName', 'VARCHAR', false, 50);

		$tMap->addColumn('DATE_ADDED', 'DateAdded', 'TIMESTAMP', false, null);

		$tMap->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null);

		$tMap->addColumn('URL', 'Url', 'VARCHAR', false, 255);

		$tMap->addColumn('SOLVED', 'Solved', 'SMALLINT', true, 1);

	} // doBuild()

} // SfWebpanelBugsMapBuilder
