<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRegSkosProperty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reg_skos_property');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('name', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('uri', 'string', 255, array('type' => 'string', 'default' => '', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('object_type', 'enum', 8, array('type' => 'enum', 'values' => array(0 => 'resource', 1 => 'literal'), 'default' => '', 'notnull' => true, 'length' => '8'));
        $this->hasColumn('is_required', 'integer', 1, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('is_reciprocal', 'integer', 1, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('is_singleton', 'integer', 1, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('is_scheme', 'integer', 1, array('type' => 'integer', 'default' => '0', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('is_in_picklist', 'integer', 1, array('type' => 'integer', 'default' => '1', 'notnull' => true, 'length' => '1'));
        $this->hasColumn('parent_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('inverse_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('display_order', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('picklist_order', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('label', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('definition', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('comment', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('examples', 'string', 255, array('type' => 'string', 'length' => '255'));
    }

    public function setUp()
    {
        $this->hasMany('RegConceptProperty', array('local' => 'id',
                                                   'foreign' => 'skos_property_id'));

        $this->hasMany('RegConceptPropertyHistory', array('local' => 'id',
                                                          'foreign' => 'skos_property_id'));
    }
}