<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSfBlogComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_blog_comment');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('status', 'integer', 4, array('type' => 'integer', 'default' => '1', 'length' => '4'));
        $this->hasColumn('sf_blog_post_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('author_name', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('author_email', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('author_url', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('content', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('created_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    }

    public function setUp()
    {
        $this->hasOne('SfBlogPost', array('local' => 'sf_blog_post_id',
                                          'foreign' => 'id'));
    }
}