<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSfBlogPost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_blog_post');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('is_published', 'integer', 1, array('type' => 'integer', 'default' => '0', 'length' => '1'));
        $this->hasColumn('allow_comments', 'integer', 1, array('type' => 'integer', 'default' => '1', 'length' => '1'));
        $this->hasColumn('nb_comments', 'integer', 4, array('type' => 'integer', 'default' => '0', 'length' => '4'));
        $this->hasColumn('sf_blog_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('author_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('title', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('stripped_title', 'string', 255, array('type' => 'string', 'length' => '255'));
        $this->hasColumn('extract', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('content', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
        $this->hasColumn('created_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('updated_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
        $this->hasColumn('published_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    }

    public function setUp()
    {
        $this->hasOne('SfBlog', array('local' => 'sf_blog_id',
                                      'foreign' => 'id'));

        $this->hasOne('SfGuardUser', array('local' => 'author_id',
                                           'foreign' => 'id'));

        $this->hasMany('SfBlogComment', array('local' => 'id',
                                              'foreign' => 'sf_blog_post_id'));

        $this->hasMany('SfBlogTag', array('local' => 'id',
                                          'foreign' => 'sf_blog_post_id'));
    }
}