<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSfBlogUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_blog_user');
        $this->hasColumn('id', 'integer', 4, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '4'));
        $this->hasColumn('is_creator', 'integer', 1, array('type' => 'integer', 'default' => '1', 'length' => '1'));
        $this->hasColumn('sf_blog_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
        $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));
    }

    public function setUp()
    {
        $this->hasOne('SfBlog', array('local' => 'sf_blog_id',
                                      'foreign' => 'id'));

        $this->hasOne('SfGuardUser', array('local' => 'user_id',
                                           'foreign' => 'id'));
    }
}