<?php slot('feeds');
  $rss['link'] = "@schema_history_feed_rss?IdType=" . $sf_params->get('IdType') . "&id=" . $sf_params->get('id');
  $rdf['link'] = "@schema_history_feed_rdf?IdType=" . $sf_params->get('IdType') . "&id=" . $sf_params->get('id');
  $atom['link'] = "@schema_history_feed_atom?IdType=" . $sf_params->get('IdType') . "&id=" . $sf_params->get('id');
  $rss['title'] = "RSS 2.01 History Feed";
  $rdf['title'] = "RSS 1.0 (RDF) History Feed";
  $atom['title'] = "Atom 1.0 History Feed";
  ?>
<?php echo auto_discovery_link_tag('rss', $rss['link'], $rss) ?>
<?php echo auto_discovery_link_tag('rdf', $rdf['link'], $rdf) ?>
<?php echo auto_discovery_link_tag('rss', $atom['link'], $atom) ?>
<?php end_slot() ?>
<?php
// auto-generated by sfPropelAdmin
// date: 2009/06/26 23:03:12
?>
<ul class="sf_admin_actions">
  <li>
    <?php echo link_to('rss2', $rss['link'], array(
      "rel"   => "alternate",
      "type"  => "application/rss+xml",
      "title" => $rss['title']));
    ?>
  </li>
  <li>
    <?php echo link_to('rss1', $rdf['link'], array(
      "rel"   => "alternate",
      "type"  => "application/rdf+xml",
      "title" => $rdf['title']));
    ?>
  </li>
  <li>
    <?php echo link_to('atom', $atom['link'], array(
      "rel"   => "alternate",
      "type"  => "application/atom+xml",
      "title" => $atom['title']));
    ?>
  </li>
  <li><img align="top" alt="Feed-icon" src="/images/feed-icon.gif" style="width: 16px; height: 16px;"/></li>
</ul>
