<?php


/**
 * This class adds structure of 'reg_agent' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Apr 22 15:10:10 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AgentMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AgentMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AgentPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AgentPeer::TABLE_NAME);
		$tMap->setPhpName('Agent');
		$tMap->setClassname('Agent');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('LAST_UPDATED', 'LastUpdated', 'TIMESTAMP', true, null);

		$tMap->addColumn('DELETED_AT', 'DeletedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('ORG_EMAIL', 'OrgEmail', 'VARCHAR', true, 100);

		$tMap->addColumn('ORG_NAME', 'OrgName', 'VARCHAR', true, 255);

		$tMap->addColumn('IND_AFFILIATION', 'IndAffiliation', 'VARCHAR', false, 255);

		$tMap->addColumn('IND_ROLE', 'IndRole', 'VARCHAR', false, 45);

		$tMap->addColumn('ADDRESS1', 'Address1', 'VARCHAR', false, 255);

		$tMap->addColumn('ADDRESS2', 'Address2', 'VARCHAR', false, 255);

		$tMap->addColumn('CITY', 'City', 'VARCHAR', false, 45);

		$tMap->addColumn('STATE', 'State', 'CHAR', false, 2);

		$tMap->addColumn('POSTAL_CODE', 'PostalCode', 'VARCHAR', false, 15);

		$tMap->addColumn('COUNTRY', 'Country', 'CHAR', false, 3);

		$tMap->addColumn('PHONE', 'Phone', 'VARCHAR', false, 45);

		$tMap->addColumn('WEB_ADDRESS', 'WebAddress', 'VARCHAR', false, 255);

		$tMap->addColumn('TYPE', 'Type', 'CHAR', false, 15);

	} // doBuild()

} // AgentMapBuilder
