<?php


/**
 * This class adds structure of 'profile_property' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Apr 22 15:10:10 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ProfilePropertyMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ProfilePropertyMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ProfilePropertyPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ProfilePropertyPeer::TABLE_NAME);
		$tMap->setPhpName('ProfileProperty');
		$tMap->setClassname('ProfileProperty');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('DELETED_AT', 'DeletedAt', 'TIMESTAMP', false, null);

		$tMap->addForeignKey('CREATED_BY', 'CreatedBy', 'INTEGER', 'reg_user', 'ID', false, null);

		$tMap->addForeignKey('UPDATED_BY', 'UpdatedBy', 'INTEGER', 'reg_user', 'ID', false, null);

		$tMap->addForeignKey('DELETED_BY', 'DeletedBy', 'INTEGER', 'reg_user', 'ID', false, null);

		$tMap->addForeignKey('PROFILE_ID', 'ProfileId', 'INTEGER', 'profile', 'ID', true, null);

		$tMap->addForeignKey('SCHEMA_ID', 'SchemaId', 'INTEGER', 'reg_schema', 'ID', false, null);

		$tMap->addForeignKey('SCHEMA_PROPERTY_ID', 'SchemaPropertyId', 'INTEGER', 'reg_schema_property', 'ID', false, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 255);

		$tMap->addColumn('LABEL', 'Label', 'VARCHAR', true, 255);

		$tMap->addColumn('DEFINITION', 'Definition', 'LONGVARCHAR', false, null);

		$tMap->addColumn('COMMENT', 'Comment', 'LONGVARCHAR', false, null);

		$tMap->addColumn('TYPE', 'Type', 'CHAR', true, null);

		$tMap->addColumn('URI', 'Uri', 'VARCHAR', false, 255);

		$tMap->addForeignKey('STATUS_ID', 'StatusId', 'INTEGER', 'reg_status', 'ID', true, null);

		$tMap->addColumn('LANGUAGE', 'Language', 'VARCHAR', true, 6);

		$tMap->addColumn('NOTE', 'Note', 'LONGVARCHAR', false, null);

		$tMap->addColumn('DISPLAY_ORDER', 'DisplayOrder', 'INTEGER', false, null);

		$tMap->addColumn('PICKLIST_ORDER', 'PicklistOrder', 'INTEGER', false, null);

		$tMap->addColumn('EXAMPLES', 'Examples', 'VARCHAR', false, 255);

		$tMap->addColumn('IS_REQUIRED', 'IsRequired', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_RECIPROCAL', 'IsReciprocal', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_SINGLETON', 'IsSingleton', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_IN_PICKLIST', 'IsInPicklist', 'BOOLEAN', true, null);

		$tMap->addForeignKey('INVERSE_PROFILE_PROPERTY_ID', 'InverseProfilePropertyId', 'INTEGER', 'profile_property', 'ID', false, null);

	} // doBuild()

} // ProfilePropertyMapBuilder
