<?php


/**
 * This class adds structure of 'reg_skos_property' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Apr 22 15:10:11 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SkosPropertyMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SkosPropertyMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(SkosPropertyPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(SkosPropertyPeer::TABLE_NAME);
		$tMap->setPhpName('SkosProperty');
		$tMap->setClassname('SkosProperty');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('PARENT_ID', 'ParentId', 'INTEGER', false, null);

		$tMap->addColumn('INVERSE_ID', 'InverseId', 'INTEGER', false, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 255);

		$tMap->addColumn('URI', 'Uri', 'VARCHAR', true, 255);

		$tMap->addColumn('OBJECT_TYPE', 'ObjectType', 'CHAR', true, null);

		$tMap->addColumn('DISPLAY_ORDER', 'DisplayOrder', 'INTEGER', false, null);

		$tMap->addColumn('PICKLIST_ORDER', 'PicklistOrder', 'INTEGER', false, null);

		$tMap->addColumn('LABEL', 'Label', 'VARCHAR', false, 255);

		$tMap->addColumn('DEFINITION', 'Definition', 'LONGVARCHAR', false, null);

		$tMap->addColumn('COMMENT', 'Comment', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXAMPLES', 'Examples', 'VARCHAR', false, 255);

		$tMap->addColumn('IS_REQUIRED', 'IsRequired', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_RECIPROCAL', 'IsReciprocal', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_SINGLETON', 'IsSingleton', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_SCHEME', 'IsScheme', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_IN_PICKLIST', 'IsInPicklist', 'BOOLEAN', true, null);

	} // doBuild()

} // SkosPropertyMapBuilder
