<?php

/**
 * Base class that represents a row from the 'arc_id2val' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Apr 23 17:03:53 2009
 *
 * @package    lib.model.om
 */
abstract class BaseArcId2val extends BaseObject  implements Persistent {


  const PEER = 'ArcId2valPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ArcId2valPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the misc field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $misc;

	/**
	 * The value for the val field.
	 * @var        string
	 */
	protected $val;

	/**
	 * The value for the val_type field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $val_type;

	/**
	 * @var        array ArcG2t[] Collection to store aggregation of ArcG2t objects.
	 */
	protected $collArcG2ts;

	/**
	 * @var        Criteria The criteria used to select the current contents of collArcG2ts.
	 */
	private $lastArcG2tCriteria = null;

	/**
	 * @var        array ArcTriple[] Collection to store aggregation of ArcTriple objects.
	 */
	protected $collArcTriplesRelatedByP;

	/**
	 * @var        Criteria The criteria used to select the current contents of collArcTriplesRelatedByP.
	 */
	private $lastArcTripleRelatedByPCriteria = null;

	/**
	 * @var        array ArcTriple[] Collection to store aggregation of ArcTriple objects.
	 */
	protected $collArcTriplesRelatedByOLangDt;

	/**
	 * @var        Criteria The criteria used to select the current contents of collArcTriplesRelatedByOLangDt.
	 */
	private $lastArcTripleRelatedByOLangDtCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseArcId2val object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->misc = false;
		$this->val_type = false;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [misc] column value.
	 * 
	 * @return     boolean
	 */
	public function getMisc()
	{
		return $this->misc;
	}

	/**
	 * Get the [val] column value.
	 * 
	 * @return     string
	 */
	public function getVal()
	{
		return $this->val;
	}

	/**
	 * Get the [val_type] column value.
	 * 
	 * @return     boolean
	 */
	public function getValType()
	{
		return $this->val_type;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     ArcId2val The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ArcId2valPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [misc] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ArcId2val The current object (for fluent API support)
	 */
	public function setMisc($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->misc !== $v || $v === false) {
			$this->misc = $v;
			$this->modifiedColumns[] = ArcId2valPeer::MISC;
		}

		return $this;
	} // setMisc()

	/**
	 * Set the value of [val] column.
	 * 
	 * @param      string $v new value
	 * @return     ArcId2val The current object (for fluent API support)
	 */
	public function setVal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->val !== $v) {
			$this->val = $v;
			$this->modifiedColumns[] = ArcId2valPeer::VAL;
		}

		return $this;
	} // setVal()

	/**
	 * Set the value of [val_type] column.
	 * 
	 * @param      boolean $v new value
	 * @return     ArcId2val The current object (for fluent API support)
	 */
	public function setValType($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->val_type !== $v || $v === false) {
			$this->val_type = $v;
			$this->modifiedColumns[] = ArcId2valPeer::VAL_TYPE;
		}

		return $this;
	} // setValType()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(ArcId2valPeer::MISC,ArcId2valPeer::VAL_TYPE))) {
				return false;
			}

			if ($this->misc !== false) {
				return false;
			}

			if ($this->val_type !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->misc = ($row[$startcol + 1] !== null) ? (boolean) $row[$startcol + 1] : null;
			$this->val = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->val_type = ($row[$startcol + 3] !== null) ? (boolean) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = ArcId2valPeer::NUM_COLUMNS - ArcId2valPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating ArcId2val object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ArcId2valPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ArcId2valPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collArcG2ts = null;
			$this->lastArcG2tCriteria = null;

			$this->collArcTriplesRelatedByP = null;
			$this->lastArcTripleRelatedByPCriteria = null;

			$this->collArcTriplesRelatedByOLangDt = null;
			$this->lastArcTripleRelatedByOLangDtCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseArcId2val:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ArcId2valPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ArcId2valPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseArcId2val:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseArcId2val:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ArcId2valPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseArcId2val:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ArcId2valPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ArcId2valPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ArcId2valPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ArcId2valPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collArcG2ts !== null) {
				foreach ($this->collArcG2ts as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collArcTriplesRelatedByP !== null) {
				foreach ($this->collArcTriplesRelatedByP as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collArcTriplesRelatedByOLangDt !== null) {
				foreach ($this->collArcTriplesRelatedByOLangDt as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ArcId2valPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collArcG2ts !== null) {
					foreach ($this->collArcG2ts as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collArcTriplesRelatedByP !== null) {
					foreach ($this->collArcTriplesRelatedByP as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collArcTriplesRelatedByOLangDt !== null) {
					foreach ($this->collArcTriplesRelatedByOLangDt as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ArcId2valPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getMisc();
				break;
			case 2:
				return $this->getVal();
				break;
			case 3:
				return $this->getValType();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ArcId2valPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getMisc(),
			$keys[2] => $this->getVal(),
			$keys[3] => $this->getValType(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ArcId2valPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setMisc($value);
				break;
			case 2:
				$this->setVal($value);
				break;
			case 3:
				$this->setValType($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ArcId2valPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setMisc($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setVal($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setValType($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);

		if ($this->isColumnModified(ArcId2valPeer::ID)) $criteria->add(ArcId2valPeer::ID, $this->id);
		if ($this->isColumnModified(ArcId2valPeer::MISC)) $criteria->add(ArcId2valPeer::MISC, $this->misc);
		if ($this->isColumnModified(ArcId2valPeer::VAL)) $criteria->add(ArcId2valPeer::VAL, $this->val);
		if ($this->isColumnModified(ArcId2valPeer::VAL_TYPE)) $criteria->add(ArcId2valPeer::VAL_TYPE, $this->val_type);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);

		$criteria->add(ArcId2valPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of ArcId2val (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setMisc($this->misc);

		$copyObj->setVal($this->val);

		$copyObj->setValType($this->val_type);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getArcG2ts() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addArcG2t($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getArcTriplesRelatedByP() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addArcTripleRelatedByP($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getArcTriplesRelatedByOLangDt() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addArcTripleRelatedByOLangDt($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     ArcId2val Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ArcId2valPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ArcId2valPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collArcG2ts collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addArcG2ts()
	 */
	public function clearArcG2ts()
	{
		$this->collArcG2ts = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collArcG2ts collection (array).
	 *
	 * By default this just sets the collArcG2ts collection to an empty array (like clearcollArcG2ts());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initArcG2ts()
	{
		$this->collArcG2ts = array();
	}

	/**
	 * Gets an array of ArcG2t objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this ArcId2val has previously been saved, it will retrieve
	 * related ArcG2ts from storage. If this ArcId2val is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ArcG2t[]
	 * @throws     PropelException
	 */
	public function getArcG2ts($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collArcG2ts === null) {
			if ($this->isNew()) {
			   $this->collArcG2ts = array();
			} else {

				$criteria->add(ArcG2tPeer::G, $this->id);

				ArcG2tPeer::addSelectColumns($criteria);
				$this->collArcG2ts = ArcG2tPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ArcG2tPeer::G, $this->id);

				ArcG2tPeer::addSelectColumns($criteria);
				if (!isset($this->lastArcG2tCriteria) || !$this->lastArcG2tCriteria->equals($criteria)) {
					$this->collArcG2ts = ArcG2tPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastArcG2tCriteria = $criteria;
		return $this->collArcG2ts;
	}

	/**
	 * Returns the number of related ArcG2t objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ArcG2t objects.
	 * @throws     PropelException
	 */
	public function countArcG2ts(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collArcG2ts === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ArcG2tPeer::G, $this->id);

				$count = ArcG2tPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ArcG2tPeer::G, $this->id);

				if (!isset($this->lastArcG2tCriteria) || !$this->lastArcG2tCriteria->equals($criteria)) {
					$count = ArcG2tPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collArcG2ts);
				}
			} else {
				$count = count($this->collArcG2ts);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ArcG2t object to this object
	 * through the ArcG2t foreign key attribute.
	 *
	 * @param      ArcG2t $l ArcG2t
	 * @return     void
	 * @throws     PropelException
	 */
	public function addArcG2t(ArcG2t $l)
	{
		if ($this->collArcG2ts === null) {
			$this->initArcG2ts();
		}
		if (!in_array($l, $this->collArcG2ts, true)) { // only add it if the **same** object is not already associated
			array_push($this->collArcG2ts, $l);
			$l->setArcId2val($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this ArcId2val is new, it will return
	 * an empty collection; or if this ArcId2val has previously
	 * been saved, it will retrieve related ArcG2ts from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in ArcId2val.
	 */
	public function getArcG2tsJoinArcTriple($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collArcG2ts === null) {
			if ($this->isNew()) {
				$this->collArcG2ts = array();
			} else {

				$criteria->add(ArcG2tPeer::G, $this->id);

				$this->collArcG2ts = ArcG2tPeer::doSelectJoinArcTriple($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ArcG2tPeer::G, $this->id);

			if (!isset($this->lastArcG2tCriteria) || !$this->lastArcG2tCriteria->equals($criteria)) {
				$this->collArcG2ts = ArcG2tPeer::doSelectJoinArcTriple($criteria, $con, $join_behavior);
			}
		}
		$this->lastArcG2tCriteria = $criteria;

		return $this->collArcG2ts;
	}

	/**
	 * Clears out the collArcTriplesRelatedByP collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addArcTriplesRelatedByP()
	 */
	public function clearArcTriplesRelatedByP()
	{
		$this->collArcTriplesRelatedByP = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collArcTriplesRelatedByP collection (array).
	 *
	 * By default this just sets the collArcTriplesRelatedByP collection to an empty array (like clearcollArcTriplesRelatedByP());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initArcTriplesRelatedByP()
	{
		$this->collArcTriplesRelatedByP = array();
	}

	/**
	 * Gets an array of ArcTriple objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this ArcId2val has previously been saved, it will retrieve
	 * related ArcTriplesRelatedByP from storage. If this ArcId2val is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ArcTriple[]
	 * @throws     PropelException
	 */
	public function getArcTriplesRelatedByP($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collArcTriplesRelatedByP === null) {
			if ($this->isNew()) {
			   $this->collArcTriplesRelatedByP = array();
			} else {

				$criteria->add(ArcTriplePeer::P, $this->id);

				ArcTriplePeer::addSelectColumns($criteria);
				$this->collArcTriplesRelatedByP = ArcTriplePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ArcTriplePeer::P, $this->id);

				ArcTriplePeer::addSelectColumns($criteria);
				if (!isset($this->lastArcTripleRelatedByPCriteria) || !$this->lastArcTripleRelatedByPCriteria->equals($criteria)) {
					$this->collArcTriplesRelatedByP = ArcTriplePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastArcTripleRelatedByPCriteria = $criteria;
		return $this->collArcTriplesRelatedByP;
	}

	/**
	 * Returns the number of related ArcTriple objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ArcTriple objects.
	 * @throws     PropelException
	 */
	public function countArcTriplesRelatedByP(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collArcTriplesRelatedByP === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ArcTriplePeer::P, $this->id);

				$count = ArcTriplePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ArcTriplePeer::P, $this->id);

				if (!isset($this->lastArcTripleRelatedByPCriteria) || !$this->lastArcTripleRelatedByPCriteria->equals($criteria)) {
					$count = ArcTriplePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collArcTriplesRelatedByP);
				}
			} else {
				$count = count($this->collArcTriplesRelatedByP);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ArcTriple object to this object
	 * through the ArcTriple foreign key attribute.
	 *
	 * @param      ArcTriple $l ArcTriple
	 * @return     void
	 * @throws     PropelException
	 */
	public function addArcTripleRelatedByP(ArcTriple $l)
	{
		if ($this->collArcTriplesRelatedByP === null) {
			$this->initArcTriplesRelatedByP();
		}
		if (!in_array($l, $this->collArcTriplesRelatedByP, true)) { // only add it if the **same** object is not already associated
			array_push($this->collArcTriplesRelatedByP, $l);
			$l->setArcId2valRelatedByP($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this ArcId2val is new, it will return
	 * an empty collection; or if this ArcId2val has previously
	 * been saved, it will retrieve related ArcTriplesRelatedByP from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in ArcId2val.
	 */
	public function getArcTriplesRelatedByPJoinArcS2val($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collArcTriplesRelatedByP === null) {
			if ($this->isNew()) {
				$this->collArcTriplesRelatedByP = array();
			} else {

				$criteria->add(ArcTriplePeer::P, $this->id);

				$this->collArcTriplesRelatedByP = ArcTriplePeer::doSelectJoinArcS2val($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ArcTriplePeer::P, $this->id);

			if (!isset($this->lastArcTripleRelatedByPCriteria) || !$this->lastArcTripleRelatedByPCriteria->equals($criteria)) {
				$this->collArcTriplesRelatedByP = ArcTriplePeer::doSelectJoinArcS2val($criteria, $con, $join_behavior);
			}
		}
		$this->lastArcTripleRelatedByPCriteria = $criteria;

		return $this->collArcTriplesRelatedByP;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this ArcId2val is new, it will return
	 * an empty collection; or if this ArcId2val has previously
	 * been saved, it will retrieve related ArcTriplesRelatedByP from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in ArcId2val.
	 */
	public function getArcTriplesRelatedByPJoinArcO2val($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collArcTriplesRelatedByP === null) {
			if ($this->isNew()) {
				$this->collArcTriplesRelatedByP = array();
			} else {

				$criteria->add(ArcTriplePeer::P, $this->id);

				$this->collArcTriplesRelatedByP = ArcTriplePeer::doSelectJoinArcO2val($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ArcTriplePeer::P, $this->id);

			if (!isset($this->lastArcTripleRelatedByPCriteria) || !$this->lastArcTripleRelatedByPCriteria->equals($criteria)) {
				$this->collArcTriplesRelatedByP = ArcTriplePeer::doSelectJoinArcO2val($criteria, $con, $join_behavior);
			}
		}
		$this->lastArcTripleRelatedByPCriteria = $criteria;

		return $this->collArcTriplesRelatedByP;
	}

	/**
	 * Clears out the collArcTriplesRelatedByOLangDt collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addArcTriplesRelatedByOLangDt()
	 */
	public function clearArcTriplesRelatedByOLangDt()
	{
		$this->collArcTriplesRelatedByOLangDt = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collArcTriplesRelatedByOLangDt collection (array).
	 *
	 * By default this just sets the collArcTriplesRelatedByOLangDt collection to an empty array (like clearcollArcTriplesRelatedByOLangDt());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initArcTriplesRelatedByOLangDt()
	{
		$this->collArcTriplesRelatedByOLangDt = array();
	}

	/**
	 * Gets an array of ArcTriple objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this ArcId2val has previously been saved, it will retrieve
	 * related ArcTriplesRelatedByOLangDt from storage. If this ArcId2val is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ArcTriple[]
	 * @throws     PropelException
	 */
	public function getArcTriplesRelatedByOLangDt($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collArcTriplesRelatedByOLangDt === null) {
			if ($this->isNew()) {
			   $this->collArcTriplesRelatedByOLangDt = array();
			} else {

				$criteria->add(ArcTriplePeer::O_LANG_DT, $this->id);

				ArcTriplePeer::addSelectColumns($criteria);
				$this->collArcTriplesRelatedByOLangDt = ArcTriplePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ArcTriplePeer::O_LANG_DT, $this->id);

				ArcTriplePeer::addSelectColumns($criteria);
				if (!isset($this->lastArcTripleRelatedByOLangDtCriteria) || !$this->lastArcTripleRelatedByOLangDtCriteria->equals($criteria)) {
					$this->collArcTriplesRelatedByOLangDt = ArcTriplePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastArcTripleRelatedByOLangDtCriteria = $criteria;
		return $this->collArcTriplesRelatedByOLangDt;
	}

	/**
	 * Returns the number of related ArcTriple objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ArcTriple objects.
	 * @throws     PropelException
	 */
	public function countArcTriplesRelatedByOLangDt(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collArcTriplesRelatedByOLangDt === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ArcTriplePeer::O_LANG_DT, $this->id);

				$count = ArcTriplePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ArcTriplePeer::O_LANG_DT, $this->id);

				if (!isset($this->lastArcTripleRelatedByOLangDtCriteria) || !$this->lastArcTripleRelatedByOLangDtCriteria->equals($criteria)) {
					$count = ArcTriplePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collArcTriplesRelatedByOLangDt);
				}
			} else {
				$count = count($this->collArcTriplesRelatedByOLangDt);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ArcTriple object to this object
	 * through the ArcTriple foreign key attribute.
	 *
	 * @param      ArcTriple $l ArcTriple
	 * @return     void
	 * @throws     PropelException
	 */
	public function addArcTripleRelatedByOLangDt(ArcTriple $l)
	{
		if ($this->collArcTriplesRelatedByOLangDt === null) {
			$this->initArcTriplesRelatedByOLangDt();
		}
		if (!in_array($l, $this->collArcTriplesRelatedByOLangDt, true)) { // only add it if the **same** object is not already associated
			array_push($this->collArcTriplesRelatedByOLangDt, $l);
			$l->setArcId2valRelatedByOLangDt($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this ArcId2val is new, it will return
	 * an empty collection; or if this ArcId2val has previously
	 * been saved, it will retrieve related ArcTriplesRelatedByOLangDt from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in ArcId2val.
	 */
	public function getArcTriplesRelatedByOLangDtJoinArcS2val($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collArcTriplesRelatedByOLangDt === null) {
			if ($this->isNew()) {
				$this->collArcTriplesRelatedByOLangDt = array();
			} else {

				$criteria->add(ArcTriplePeer::O_LANG_DT, $this->id);

				$this->collArcTriplesRelatedByOLangDt = ArcTriplePeer::doSelectJoinArcS2val($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ArcTriplePeer::O_LANG_DT, $this->id);

			if (!isset($this->lastArcTripleRelatedByOLangDtCriteria) || !$this->lastArcTripleRelatedByOLangDtCriteria->equals($criteria)) {
				$this->collArcTriplesRelatedByOLangDt = ArcTriplePeer::doSelectJoinArcS2val($criteria, $con, $join_behavior);
			}
		}
		$this->lastArcTripleRelatedByOLangDtCriteria = $criteria;

		return $this->collArcTriplesRelatedByOLangDt;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this ArcId2val is new, it will return
	 * an empty collection; or if this ArcId2val has previously
	 * been saved, it will retrieve related ArcTriplesRelatedByOLangDt from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in ArcId2val.
	 */
	public function getArcTriplesRelatedByOLangDtJoinArcO2val($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ArcId2valPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collArcTriplesRelatedByOLangDt === null) {
			if ($this->isNew()) {
				$this->collArcTriplesRelatedByOLangDt = array();
			} else {

				$criteria->add(ArcTriplePeer::O_LANG_DT, $this->id);

				$this->collArcTriplesRelatedByOLangDt = ArcTriplePeer::doSelectJoinArcO2val($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ArcTriplePeer::O_LANG_DT, $this->id);

			if (!isset($this->lastArcTripleRelatedByOLangDtCriteria) || !$this->lastArcTripleRelatedByOLangDtCriteria->equals($criteria)) {
				$this->collArcTriplesRelatedByOLangDt = ArcTriplePeer::doSelectJoinArcO2val($criteria, $con, $join_behavior);
			}
		}
		$this->lastArcTripleRelatedByOLangDtCriteria = $criteria;

		return $this->collArcTriplesRelatedByOLangDt;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collArcG2ts) {
				foreach ((array) $this->collArcG2ts as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collArcTriplesRelatedByP) {
				foreach ((array) $this->collArcTriplesRelatedByP as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collArcTriplesRelatedByOLangDt) {
				foreach ((array) $this->collArcTriplesRelatedByOLangDt as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collArcG2ts = null;
		$this->collArcTriplesRelatedByP = null;
		$this->collArcTriplesRelatedByOLangDt = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseArcId2val:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseArcId2val::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseArcId2val
