#
# SQL Export
# Created by Querious (962)
# Created: April 18, 2015 at 2:06:27 PM EDT
# Encoding: Unicode (UTF-8)
#


DROP TABLE IF EXISTS `reg_rdf_namespace`;
DROP TABLE IF EXISTS `reg_prefix`;
DROP TABLE IF EXISTS `reg_file_import_history`;
DROP TABLE IF EXISTS `reg_batch`;
DROP TABLE IF EXISTS `profile_property`;


CREATE TABLE `profile_property` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  `profile_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `label` varchar(255) NOT NULL DEFAULT '',
  `definition` text,
  `comment` text,
  `type` enum('property','subproperty','class','subclass') NOT NULL DEFAULT 'property',
  `uri` varchar(255) DEFAULT NULL,
  `status_id` int(11) NOT NULL DEFAULT '1',
  `language` varchar(6) NOT NULL DEFAULT 'en',
  `note` text,
  `display_order` int(11) DEFAULT NULL COMMENT 'Display order of properties',
  `export_order` int(11) DEFAULT NULL COMMENT 'Display order of properties',
  `picklist_order` int(11) DEFAULT NULL,
  `examples` varchar(255) DEFAULT NULL COMMENT 'Link to example usage',
  `is_required` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'boolean -- id this value required',
  `is_reciprocal` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'boolean - subject and object must both have this property',
  `is_singleton` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'boolean -- is this property allowed to repeat for a concept',
  `is_in_picklist` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'boolean - is in the property picklist',
  `is_in_export` tinyint(1) NOT NULL DEFAULT '1',
  `inverse_profile_property_id` int(11) DEFAULT NULL COMMENT 'id of the inverse property',
  `is_in_class_picklist` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'boolean - is in the property picklist',
  `is_in_property_picklist` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'boolean - is in the property picklist',
  `is_in_rdf` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'boolean - should this display in the RDF',
  `is_in_xsd` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'boolean - should this display in the XSD',
  `is_attribute` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'boolean - is this an attribute? attribute''s aren''t editable outside the main form',
  `has_language` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Boolean that determines whether language attribute is displayed for this property',
  `is_object_prop` tinyint(1) NOT NULL DEFAULT '1',
  `is_in_form` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `profile_property_status_id` (`status_id`),
  KEY `profile_property_updated_by` (`updated_by`),
  KEY `profile_property_created_by` (`created_by`),
  KEY `profile_property_deleted_by` (`deleted_by`),
  KEY `inverse_profile_property_id` (`inverse_profile_property_id`),
  KEY `profile_id` (`profile_id`) USING BTREE,
  FOREIGN KEY (`profile_id`) REFERENCES `profile` (`id`) ON UPDATE NO ACTION,
  FOREIGN KEY (`inverse_profile_property_id`) REFERENCES `profile_property` (`id`),
  FOREIGN KEY (`status_id`) REFERENCES `reg_status` (`id`),
  FOREIGN KEY (`updated_by`) REFERENCES `reg_user` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  FOREIGN KEY (`created_by`) REFERENCES `reg_user` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  FOREIGN KEY (`deleted_by`) REFERENCES `reg_user` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=1170;


CREATE TABLE `reg_batch` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `run_time` datetime DEFAULT NULL,
  `run_description` text CHARACTER SET latin1,
  `object_type` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  `object_id` int(11) DEFAULT NULL,
  `event_time` datetime DEFAULT NULL,
  `event_type` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  `event_description` text CHARACTER SET latin1,
  `registry_uri` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AVG_ROW_LENGTH=331 PACK_KEYS=0 ROW_FORMAT=COMPACT COMMENT='InnoDB free: 5120 kB';


CREATE TABLE `reg_file_import_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `map` text COMMENT 'stores the serialized column map array',
  `user_id` int(11) DEFAULT NULL,
  `vocabulary_id` int(11) DEFAULT NULL,
  `schema_id` int(11) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `source_file_name` varchar(255) DEFAULT NULL,
  `file_type` varchar(30) DEFAULT NULL,
  `batch_id` int(11) DEFAULT NULL,
  `results` text COMMENT 'stores the serialized results of the import',
  `total_processed_count` int(11) DEFAULT NULL,
  `error_count` int(11) DEFAULT NULL,
  `success_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `vocabulary_id` (`vocabulary_id`),
  KEY `schema_id` (`schema_id`),
  KEY `batch_id` (`batch_id`),
  FOREIGN KEY (`user_id`) REFERENCES `reg_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (`vocabulary_id`) REFERENCES `reg_vocabulary` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (`schema_id`) REFERENCES `reg_schema` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (`batch_id`) REFERENCES `reg_batch` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 PACK_KEYS=0 ROW_FORMAT=COMPACT;


CREATE TABLE `reg_prefix` (
  `prefix` varchar(40) NOT NULL,
  `uri` varchar(256) DEFAULT NULL,
  `rank` int(11) DEFAULT '0',
  PRIMARY KEY (`prefix`),
  KEY `prefix_uri` (`uri`(255)),
  KEY `prefix_rank` (`rank`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `reg_rdf_namespace` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `schema_id` int(11) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `created_user_id` int(11) DEFAULT NULL,
  `updated_user_id` int(11) DEFAULT NULL,
  `token` varchar(255) NOT NULL DEFAULT '',
  `note` text,
  `uri` varchar(255) NOT NULL DEFAULT '',
  `schema_location` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `schema_id` (`schema_id`),
  FOREIGN KEY (`schema_id`) REFERENCES `reg_schema` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 PACK_KEYS=0 ROW_FORMAT=COMPACT;




SET @PREVIOUS_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;


LOCK TABLES `profile_property` WRITE;
ALTER TABLE `profile_property` DISABLE KEYS;
INSERT INTO `profile_property` (`id`, `created_at`, `updated_at`, `deleted_at`, `created_by`, `updated_by`, `deleted_by`, `profile_id`, `name`, `label`, `definition`, `comment`, `type`, `uri`, `status_id`, `language`, `note`, `display_order`, `export_order`, `picklist_order`, `examples`, `is_required`, `is_reciprocal`, `is_singleton`, `is_in_picklist`, `is_in_export`, `inverse_profile_property_id`, `is_in_class_picklist`, `is_in_property_picklist`, `is_in_rdf`, `is_in_xsd`, `is_attribute`, `has_language`, `is_object_prop`, `is_in_form`) VALUES
	(1,'2008-04-20 12:00:00','2008-04-20 15:00:00',NULL,36,36,NULL,1,'name','name',NULL,NULL,'property','reg:name',1,'en',NULL,1,3,1,NULL,1,0,1,0,1,NULL,0,0,1,1,1,1,0,1),
	(2,'2008-04-20 12:00:00','2008-04-20 15:00:00',NULL,36,36,NULL,1,'label','label',NULL,NULL,'property','rdfs:label',1,'en',NULL,2,4,2,NULL,1,0,1,1,1,NULL,1,1,1,1,0,1,0,1),
	(3,'2008-04-20 12:01:00','2008-04-20 15:01:01',NULL,36,36,NULL,1,'definition','description',NULL,NULL,'property','skos:definition',1,'en',NULL,3,6,3,NULL,0,0,0,1,1,NULL,1,1,1,1,0,1,0,1),
	(4,'2008-04-20 12:02:00','2008-04-20 15:02:00',NULL,36,36,NULL,1,'type','type',NULL,NULL,'property','rdf:type',1,'en',NULL,5,2,5,NULL,1,0,1,0,1,NULL,0,0,1,1,1,0,0,1),
	(5,'2008-04-20 00:02:00','2008-04-20 03:02:02',NULL,36,36,NULL,1,'comment','comment',NULL,NULL,'property','rdfs:comment',1,'en',NULL,4,8,4,NULL,0,0,0,1,1,NULL,1,1,1,1,0,1,0,1),
	(6,'2008-04-20 00:03:00','2008-04-20 15:03:00',NULL,36,36,NULL,1,'isSubpropertyOf','subPropertyOf',NULL,NULL,'property','rdfs:subPropertyOf',1,'en',NULL,6,14,6,NULL,0,0,0,1,1,8,0,1,1,1,0,0,1,0),
	(7,'2008-04-20 00:04:00','2008-04-20 03:04:00',NULL,36,36,NULL,1,'note','note',NULL,NULL,'property','skos:scopeNote',1,'en',NULL,8,7,8,NULL,0,0,0,1,1,NULL,1,1,1,1,0,1,0,1),
	(8,'2008-04-20 12:05:00','2008-04-20 15:05:00',NULL,36,36,NULL,1,'hasSubproperty','hasSubproperty',NULL,NULL,'property','reg:hasSubproperty',1,'en',NULL,7,15,7,NULL,0,0,0,0,0,6,0,0,1,1,1,0,1,0),
	(9,'2009-03-07 11:49:27','2009-03-07 14:49:27',NULL,36,36,NULL,1,'isSubclassOf','subClassOf','','','property','rdfs:subClassOf',1,'en','',9,12,9,'',0,0,0,0,1,10,1,0,1,1,0,0,1,0),
	(10,'2009-03-07 11:53:34','2009-03-07 14:53:34',NULL,36,36,NULL,1,'hasSubClass','hasSubClass',NULL,NULL,'property','reg:hasSubClass',1,'en',NULL,10,13,10,NULL,0,0,0,0,0,9,1,0,1,1,1,0,1,0),
	(11,'2009-03-07 11:57:15','2009-03-07 14:57:15',NULL,36,36,NULL,1,'domain','domain',NULL,NULL,'property','rdfs:domain',1,'en',NULL,11,9,11,NULL,0,0,1,1,1,NULL,0,1,1,1,0,0,1,1),
	(12,'2009-03-07 12:01:38','2009-03-07 15:01:38',NULL,36,36,NULL,1,'orange','range',NULL,NULL,'property','rdfs:range',1,'en',NULL,12,10,12,NULL,0,0,1,1,1,NULL,0,1,1,1,0,0,1,1),
	(13,'2009-03-07 12:01:38','2009-03-07 15:01:38',NULL,36,36,NULL,1,'uri','uri',NULL,NULL,'property','reg:uri',1,'en',NULL,0,1,13,NULL,1,0,1,0,1,NULL,0,0,0,1,1,0,1,1),
	(14,'2009-03-07 12:01:38','2009-03-07 15:01:38',NULL,36,36,NULL,1,'statusId','status',NULL,NULL,'property','reg:status',1,'en',NULL,27,26,27,NULL,1,0,1,0,1,NULL,0,0,0,1,1,0,1,1),
	(15,'2011-09-29 14:12:00','2011-09-29 10:20:25',NULL,36,36,NULL,1,'isInverseOf','inverseOf','','The property that determines that two given properties are inverse.','property','owl:inverseOf',1,'en','',15,16,15,'',0,1,1,1,1,NULL,0,1,1,0,0,0,1,0),
	(16,'2011-09-29 14:23:24','2011-09-29 10:23:24',NULL,36,36,NULL,1,'isSameAs','sameAs','','The property that determines that two given individuals are equal.','property','owl:sameAs',1,'en','',16,17,16,'',0,1,0,1,1,NULL,1,1,1,0,0,0,1,0),
	(17,'2011-09-29 14:26:25','2011-09-29 10:26:25',NULL,36,36,NULL,1,'propertyIsDisjointWith','propertyDisjointWith','','Used to specify that two properties are mutually disjoint, and it is defined as a property itself. ','property','owl:propertyDisjointWith',1,'en','',17,18,17,'',0,1,0,1,1,NULL,0,1,1,1,0,0,1,0),
	(18,'2011-09-29 14:28:57','2011-09-29 10:28:57',NULL,36,36,NULL,1,'isEquivalentClass','equivalentClass','','The property that determines that two given classes are equivalent, and that is used to specify datatype definitions.','property','owl:equivalentClass',1,'en','',19,20,19,'',0,1,1,1,1,NULL,1,0,1,1,0,0,1,0),
	(19,'2011-09-29 14:30:00','2011-09-29 10:30:00',NULL,36,36,NULL,1,'isEquivalentProperty','equivalentProperty','','','property','owl:equivalentProperty',1,'en','',20,21,20,'',0,1,1,1,1,NULL,0,1,1,1,0,0,1,0),
	(20,'2012-02-02 23:21:08','2012-02-02 18:21:08',NULL,36,36,NULL,1,'isDisjointWith','disjointWith','','The property that determines that two given properties are disjoint.','property','owl:disjointWith',1,'en','',18,19,18,'',0,1,0,1,1,NULL,1,1,1,1,0,0,1,0),
	(21,'2012-06-02 23:21:08','2012-06-02 19:21:08',NULL,36,36,NULL,1,'altLabel','altLabel',NULL,NULL,'property','skos:altLabel',1,'en',NULL,21,22,21,NULL,0,0,0,1,1,NULL,1,1,1,1,0,1,0,0),
	(23,'2014-01-18 04:04:02','2014-01-17 23:04:02',NULL,36,36,NULL,1,'narrowMatch','narrowMatch',NULL,NULL,'property','skos:narrowMatch',1,'en',NULL,24,25,24,NULL,0,0,0,1,1,NULL,1,1,1,1,0,0,1,0),
	(24,'2014-01-18 04:04:01','2014-01-17 23:04:01',NULL,36,36,NULL,1,'closeMatch','closeMatch',NULL,NULL,'property','skos:closeMatch',1,'en',NULL,23,24,23,NULL,0,0,0,1,1,NULL,1,1,1,1,0,0,1,0),
	(25,'2014-01-18 04:04:00','2014-01-17 23:04:00',NULL,36,36,NULL,1,'broadMatch','broadMatch',NULL,NULL,'property','skos:broadMatch',1,'en',NULL,22,23,22,NULL,0,0,0,1,1,NULL,1,1,1,1,0,0,1,0),
	(26,'2011-09-29 14:23:24','2011-09-29 10:23:24',NULL,36,36,NULL,1,'hasUnconstrained','hasUnconstrained','','','property','reg:hasUnconstrained',1,'en','',26,11,26,'',0,1,1,1,1,NULL,1,1,1,0,0,0,1,0),
	(27,'2011-09-29 14:23:24','2011-09-29 10:23:24',NULL,36,36,NULL,1,'lexicalAlias','lexicalAlias','','','property','reg:lexicalAlias',1,'en','',25,5,25,'',0,0,1,1,1,NULL,1,1,1,0,0,1,1,1),
	(30,'2015-05-01 23:04:00','2015-05-01 23:04:00',NULL,36,36,NULL,1,'changeNote','changeNote',NULL,NULL,'property','skos:changeNote',1,'en',NULL,30,30,30,NULL,0,0,0,1,1,NULL,1,1,1,1,0,1,0,0),
	(31,'2014-04-17 23:04:00','2014-04-17 23:04:00',NULL,36,36,NULL,1,'instructionNumber','instructionNumber','RDA Toolkit instruction number reference','','property','rdakit:instructionNumber',1,'en','',27,27,27,'',0,0,1,1,1,NULL,0,1,1,0,0,0,0,0);
ALTER TABLE `profile_property` ENABLE KEYS;
UNLOCK TABLES;


LOCK TABLES `reg_batch` WRITE;
ALTER TABLE `reg_batch` DISABLE KEYS;
ALTER TABLE `reg_batch` ENABLE KEYS;
UNLOCK TABLES;


LOCK TABLES `reg_file_import_history` WRITE;
ALTER TABLE `reg_file_import_history` DISABLE KEYS;
ALTER TABLE `reg_file_import_history` ENABLE KEYS;
UNLOCK TABLES;


LOCK TABLES `reg_prefix` WRITE;
ALTER TABLE `reg_prefix` DISABLE KEYS;
INSERT INTO `reg_prefix` (`prefix`, `uri`, `rank`) VALUES
	('aair','http://xmlns.notu.be/aair#',544),
	('aapi','http://rdf.alchemyapi.com/rdf/v1/s/aapi-schema#',691),
	('aat','http://vocab.getty.edu/aat/',982),
	('abc','http://www.metadata.net/harmony/ABCSchemaV5Commented.rdf#',153),
	('abs','http://abs.270a.info/dataset/',1340),
	('ac','http://umbel.org/umbel/ac/',123),
	('acc','http://purl.org/NET/acc#',200),
	('acco','http://purl.org/acco/ns#',438),
	('accom','http://purl.org/acco/ns#',1166),
	('acl','http://www.w3.org/ns/auth/acl#',159),
	('acm','http://www.rkbexplorer.com/ontologies/acm#',139),
	('acrt','http://privatealpha.com/ontology/certification/1#',1442),
	('act','http://www.w3.org/2007/rif-builtin-action#',445),
	('ad','http://schemas.talis.com/2005/address/schema#',63),
	('address','http://schemas.talis.com/2005/address/schema#',510),
	('admin','http://webns.net/mvcb/',50),
	('admingeo','http://data.ordnancesurvey.co.uk/ontology/admingeo/',265),
	('adms','http://www.w3.org/ns/adms#',423),
	('admssw','http://purl.org/adms/sw/',737),
	('aerols','http://xmlns.com/aerols/0.1/',711),
	('aers','http://aers.data2semantics.org/resource/',901),
	('aersv','http://aers.data2semantics.org/vocab/',831),
	('af','http://purl.org/ontology/af/',83),
	('affy','http://www.affymetrix.com/community/publications/affymetrix/tmsplice#',218),
	('affymetrix','http://bio2rdf.org/affymetrix_vocabulary:',1416),
	('afn','http://jena.hpl.hp.com/ARQ/function#',91),
	('agent','http://eulersharp.sourceforge.net/2003/03swap/agent#',566),
	('agents','http://eulersharp.sourceforge.net/2003/03swap/agent#',470),
	('agetec','http://www.agetec.org/',513),
	('agg','http://purl.org/twc/health/vocab/aggregate/',757),
	('agls','http://www.agls.gov.au/agls/terms/',1099),
	('agrd','http://agrinepaldata.com/',1288),
	('agrelon','http://d-nb.info/standards/elementset/agrelon#',861),
	('agro','http://agrinepaldata.com/vocab/',1281),
	('aifb','http://www.aifb.kit.edu/id/',375),
	('aigp','http://swat.cse.lehigh.edu/resources/onto/aigp.owl#',938),
	('aiiso','http://purl.org/vocab/aiiso/schema#',40),
	('aims','http://aims.fao.org/aos/common/',648),
	('air','http://dig.csail.mit.edu/TAMI/2007/amord/air#',61),
	('airport','http://www.daml.org/2001/10/html/airport-ont#',269),
	('akt','http://www.aktors.org/ontology/portal#',24),
	('akts','http://www.aktors.org/ontology/support#',132),
	('alchemy','http://rdf.alchemyapi.com/rdf/v1/s/aapi-schema#',1094),
	('algo','http://securitytoolbox.appspot.com/securityAlgorithms#',953),
	('am','http://vocab.deri.ie/am#',352),
	('amalgame','http://purl.org/vocabularies/amalgame#',1020),
	('anca','http://users.utcluj.ro/~raluca/rdf_ontologies_ralu/ralu_modified_ontology_pizzas2_0#',428),
	('aneo','http://akonadi-project.org/ontologies/aneo#',625),
	('ann','http://www.w3.org/2000/10/annotation-ns#',617),
	('ao','http://purl.org/ontology/ao/core#',400),
	('aos','http://rdf.muninn-project.org/ontologies/appearances#',971),
	('api','http://purl.org/linked-data/api/vocab#',1089),
	('apivc','http://purl.org/linked-data/api/vocab#',600),
	('app','http://jmvanel.free.fr/ontology/software_applications.n3#',1208),
	('arch','http://purl.org/archival/vocab/arch#',491),
	('archdesc','http://archdesc.info/archEvent#',1090),
	('arecipe','http://purl.org/amicroformat/arecipe/',689),
	('arg','http://rdfs.org/sioc/argument#',694),
	('arpfo','http://vocab.ouls.ox.ac.uk/projectfunding#',578),
	('article','http://ogp.me/ns/article#',1219),
	('artstor','http://simile.mit.edu/2003/10/ontologies/artstor#',766),
	('asgv','http://aims.fao.org/aos/agrovoc/',1221),
	('asn','http://purl.org/ASN/schema/core/',730),
	('ass','http://uptheasset.org/ontology#',545),
	('atom','http://www.w3.org/2005/Atom/',214),
	('atomix','http://buzzword.org.uk/rdf/atomix#',229),
	('atomowl','http://bblfish.net/work/atom-owl/2006-06-06/#',595),
	('atomrdf','http://atomowl.org/ontologies/atomrdf#',765),
	('audio','http://purl.org/media/audio#',202),
	('awol','http://bblfish.net/work/atom-owl/2006-06-06/#',383),
	('aws','http://purl.oclc.org/NET/ssnx/meteo/aws#',1424),
	('b2bo','http://purl.org/b2bo#',355),
	('b2rpubchem','http://bio2rdf.org/ns/ns/ns/pubchem#',885),
	('babelnet','http://babelnet.org/2.0/',1301),
	('bag','http://lod.geodan.nl/vocab/bag#',1319),
	('basic','http://def.seegrid.csiro.au/isotc211/iso19103/2005/basic#',1391),
	('bbc','http://www.bbc.co.uk/ontologies/news/',1029),
	('bbccms','http://www.bbc.co.uk/ontologies/cms/',1426),
	('bbccore','http://www.bbc.co.uk/ontologies/coreconcepts/',1429),
	('bbcprov','http://www.bbc.co.uk/ontologies/provenance/',1411),
	('bcnbio','http://datos.bcn.cl/ontologies/bcn-biographies#',916),
	('bcncon','http://datos.bcn.cl/ontologies/bcn-congress#',931),
	('bcngeo','http://datos.bcn.cl/ontologies/bcn-geographics#',877),
	('bcnnorms','http://datos.bcn.cl/ontologies/bcn-norms#',654),
	('bco','http://purl.obolibrary.org/obo/bco.owl#',1272),
	('bd','http://www.bigdata.com/rdf/search#',825),
	('being','http://purl.org/ontomedia/ext/common/being#',1198),
	('bevon','http://rdfs.co/bevon/',1418),
	('bf','http://bibframe.org/vocab/',563),
	('bgn','http://bibliograph.net/schemas/',1405),
	('bib','http://zeitkunst.org/bibtex/0.1/bibtex.owl#',351),
	('bibframe','http://bibframe.org/vocab/',1069),
	('biblio','http://purl.org/net/biblio#',79),
	('bibo','http://purl.org/ontology/bibo/',26),
	('bibtex','http://purl.oclc.org/NET/nknouf/ns/bibtex#',217),
	('bif','http://www.openlinksw.com/schema/sparql/extensions#',649),
	('bihap','http://bihap.kb.gov.tr/ontology/',1182),
	('bill','http://www.rdfabout.com/rdf/schema/usbill/',49),
	('bing','http://bing.com/schema/media/',875),
	('bio','http://purl.org/vocab/bio/0.1/',56),
	('bio2rdf','http://bio2rdf.org/',169),
	('biocore','http://bio2rdf.org/core#',154),
	('biol','http://purl.org/NET/biol/ns#',216),
	('biopax','http://www.biopax.org/release/biopax-level3.owl#',512),
	('biordf','http://purl.org/net/biordfmicroarray/ns#',780),
	('bioskos','http://eulersharp.sourceforge.net/2003/03swap/bioSKOSSchemes#',526),
	('biotop','http://purl.org/biotop/biotop.owl#',1071),
	('biro','http://purl.org/spar/biro/',1128),
	('bis','http://bis.270a.info/dataset/',1367),
	('bk','http://www.provbook.org/ns/#',1238),
	('blt','http://data.bl.uk/schema/bibliographic#',896),
	('bm','http://bio2rdf.org/',963),
	('bmo','http://collection.britishmuseum.org/id/ontology/',1396),
	('bne','http://datos.bne.es/resource/',768),
	('book','http://purl.org/NET/book/vocab#',67),
	('bookmark','http://www.w3.org/2002/01/bookmark#',433),
	('botany','http://purl.org/NET/biol/botany#',69),
	('bp','http://open-services.net/ns/basicProfile#',702),
	('br','http://vocab.deri.ie/br#',640),
	('bsb','http://lod.b3kat.de/title/',1047),
	('bsbm','http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/',284),
	('bte','http://purl.org/twc/vocab/between-the-edges/',707),
	('bwb','http://doc.metalex.eu/bwb/ontology/',1180),
	('c4dm','http://purl.org/NET/c4dm/event.owl#',823),
	('c4n','http://vocab.deri.ie/c4n#',288),
	('c4o','http://purl.org/spar/c4o/',531),
	('cal','http://www.w3.org/2002/12/cal/ical#',85),
	('call','http://webofcode.org/wfn/call:',1254),
	('calli','http://callimachusproject.org/rdf/2009/framework#',699),
	('camelot','http://vocab.ox.ac.uk/camelot#',1081),
	('campsite','http://www.openlinksw.com/campsites/schema#',717),
	('cao','http://purl.org/makolab/caont/',749),
	('card','http://www.ashutosh.com/test/',546),
	('care','http://eulersharp.sourceforge.net/2003/03swap/care#',580),
	('carfo','http://purl.org/carfo#',820),
	('category','http://dbpedia.org/resource/Category:',690),
	('cb','http://cbasewrap.ontologycentral.com/vocab#',1105),
	('cbase','http://ontologycentral.com/2010/05/cb/vocab#',1027),
	('cc','http://creativecommons.org/ns#',48),
	('ccard','http://purl.org/commerce/creditcard#',645),
	('cco','http://purl.org/ontology/cco/core#',330),
	('ccom','http://purl.org/ontology/cco/mappings#',594),
	('ccrel','http://creativecommons.org/ns#',1430),
	('cdc','http://www.contextdatacloud.org/resource/',1328),
	('cdm','http://purl.org/twc/ontology/cdm.owl#',535),
	('cdtype','http://purl.org/cld/cdtype/',995),
	('centrifuge','http://purl.org/twc/vocab/centrifuge#',1005),
	('ceo','http://www.ebusiness-unibw.org/ontologies/consumerelectronics/v1#',553),
	('cerif','http://spi-fm.uca.es/neologism/cerif#',747),
	('cert','http://www.w3.org/ns/auth/cert#',121),
	('cex','http://purl.org/weso/ontology/computex#',1075),
	('cf','http://mmisw.org/ont/cf/parameter/',932),
	('cfp','http://sw.deri.org/2005/08/conf/cfp.owl#',96),
	('cgov','http://reference.data.gov.uk/def/central-government/',677),
	('chebi','http://bio2rdf.org/chebi:',829),
	('cheminf','http://www.semanticweb.org/ontologies/cheminf.owl#',661),
	('chord','http://purl.org/ontology/chord/',166),
	('cidoc','http://erlangen-crm.org/current/',561),
	('cidoccrm','http://purl.org/NET/cidoc-crm/core#',679),
	('cis','http://purl.org/NET/cloudisus#',858),
	('cito','http://purl.org/spar/cito/',456),
	('citof','http://www.essepuntato.it/2013/03/cito-functions#',1412),
	('city','http://datos.localidata.com/def/City#',948),
	('cjr','http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#',1244),
	('cl','http://advene.org/ns/cinelab/',1324),
	('cld','http://purl.org/cld/terms/',76),
	('climb','http://climb.dataincubator.org/vocabs/climb/',290),
	('clineva','http://www.agfa.com/w3c/2009/clinicalEvaluation#',567),
	('clinproc','http://www.agfa.com/w3c/2009/clinicalProcedure#',615),
	('cmd','http://clarin.eu/cmd#',1234),
	('cmdi','http://www.clarin.eu/cmd/',1306),
	('cmdm','http://infra.clarin.eu/cmd/',1316),
	('cmo','http://purl.org/twc/ontologies/cmo.owl#',597),
	('cmp','http://www.ontologydesignpatterns.org/cp/owl/componency.owl#',98),
	('cnt','http://www.w3.org/2011/content#',142),
	('co','http://rhizomik.net/ontologies/copyrightonto.owl#',81),
	('code','http://telegraphis.net/ontology/measurement/code#',236),
	('coeus','http://bioinformatics.ua.pt/coeus/',710),
	('cogs','http://vocab.deri.ie/cogs#',705),
	('coin','http://purl.org/court/def/2009/coin#',392),
	('cold','http://purl.org/configurationontology#',1116),
	('coll','http://purl.org/co/',1192),
	('com','http://purl.org/commerce#',529),
	('comm','http://vocab.resc.info/communication#',1152),
	('commerce','http://search.yahoo.com/searchmonkey/commerce/',25),
	('common','http://www.w3.org/2007/uwa/context/common.owl#',341),
	('commons','http://commons.psi.enakting.org/def/',560),
	('compass','http://purl.org/net/compass#',176),
	('con','http://www.w3.org/2000/10/swap/pim/contact#',116),
	('conf','http://richard.cyganiak.de/2007/pubby/config.rdf#',1010),
	('conserv','http://conserv.deri.ie/ontology#',385),
	('contact','http://www.w3.org/2000/10/swap/pim/contact#',254),
	('content','http://purl.org/rss/1.0/modules/content/',34),
	('contsem','http://contsem.unizar.es/def/sector-publico/contratacion#',1239),
	('conv','http://purl.org/twc/vocab/conversion/',388),
	('conversion','http://purl.org/twc/vocab/conversion/',476),
	('coo','http://purl.org/coo/ns#',657),
	('copyright','http://rhizomik.net/ontologies/copyrightonto.owl#',274),
	('cordis','http://www4.wiwiss.fu-berlin.de/cordis/resource/cordis/',592),
	('core','http://vivoweb.org/ontology/core#',340),
	('coref','http://www.rkbexplorer.com/ontologies/coref#',237),
	('cos','http://www.inria.fr/acacia/corese#',495),
	('cosmo','http://purl.org/ontology/cosmo#',1095),
	('coun','http://www.daml.org/2001/09/countries/iso-3166-ont#',1161),
	('countries','http://eulersharp.sourceforge.net/2003/03swap/countries#',490),
	('courseware','http://courseware.rkbexplorer.com/ontologies/courseware#',183),
	('cpa','http://www.ontologydesignpatterns.org/schemas/cpannotationschema.owl#',1167),
	('cpant','http://purl.org/NET/cpan-uri/terms#',1451),
	('cpm','http://catalogus-professorum.org/cpm/',607),
	('cpv','http://purl.org/weso/cpv/',453),
	('crm','http://www.cidoc-crm.org/cidoc-crm/',273),
	('cro','http://rhizomik.net/ontologies/copyrightonto.owl#',990),
	('crsw','http://courseware.rkbexplorer.com/ontologies/courseware#',1196),
	('crtv','http://open-services.net/ns/crtv#',894),
	('crv','http://purl.org/twc/vocab/datacarver#',965),
	('crypto','http://www.w3.org/2000/10/swap/crypto#',376),
	('cs','http://purl.org/vocab/changeset/schema#',87),
	('csm','http://purl.org/csm/1.0#',1025),
	('csp','http://vocab.deri.ie/csp#',1137),
	('csv','http://vocab.sindice.net/csv/',1245),
	('ct','http://data.linkedct.org/resource/linkedct/',412),
	('ctag','http://commontag.org/ns#',74),
	('ctorg','http://purl.org/ctic/infraestructuras/organizacion#',1073),
	('cts2','http://schema.omg.org/spec/CTS2/1.0/',864),
	('cube','http://purl.org/linked-data/cube#',579),
	('curr','https://w3id.org/cc#',911),
	('custom','http://www.openrdf.org/config/sail/custom#',283),
	('cv','http://purl.org/captsolo/resume-rdf/0.2/cv#',60),
	('cvbase','http://purl.org/captsolo/resume-rdf/0.2/base#',913),
	('cyc','http://sw.opencyc.org/concept/',29),
	('cycann','http://sw.cyc.com/CycAnnotations_v1#',319),
	('d2r','http://sites.wiwiss.fu-berlin.de/suhl/bizer/d2r-server/config.rdf#',720),
	('d2rq','http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#',52),
	('dady','http://purl.org/NET/dady#',379),
	('daia','http://purl.org/ontology/daia/',73),
	('daiaserv','http://purl.org/ontology/daia/Service/',874),
	('dailymed','http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/',234),
	('daisy','http://www.daisy.org/z3998/2012/vocab/',1014),
	('daml','http://www.daml.org/2001/03/daml+oil#',147),
	('dannet','http://www.wordnet.dk/owl/instance/2009/03/instances/',1455),
	('datafaqs','http://purl.org/twc/vocab/datafaqs#',605),
	('dawgt','http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#',807),
	('days','http://ontologi.es/days#',82),
	('dayta','http://dayta.me/resource#',435),
	('db','http://dbpedia.org/',155),
	('dbc','http://dbpedia.org/resource/Category:',1068),
	('dblp','http://dblp.l3s.de/d2r/page/authors/',339),
	('dbnary','http://kaiko.getalp.org/dbnary#',547),
	('dbo','http://dbpedia.org/ontology/',9),
	('dbp','http://dbpedia.org/property/',4),
	('dbpedia','http://dbpedia.org/resource/',23),
	('dbpedia2','http://dbpedia.org/property/',1231),
	('dbpediaowl','http://dbpedia.org/ontology/',192),
	('dbpo','http://dbpedia.org/ontology/',872),
	('dbpp','http://dbpedia.org/property/',390),
	('dbpprop','http://dbpedia.org/property/',28),
	('dbpr','http://dbpedia.org/resource/',1145),
	('dbprop','http://dbpedia.org/property/',418),
	('dbptmpl','http://dbpedia.org/resource/Template:',1015),
	('dbr','http://dbpedia.org/resource/',113),
	('dbrc','http://dbpedia.org/resource/Category:',1216),
	('dbt','http://dbpedia.org/resource/Template:',1154),
	('dbtont','http://dbtropes.org/ont/',987),
	('dbug','http://ontologi.es/doap-bugs#',1327),
	('dbyago','http://dbpedia.org/class/yago/',834),
	('dc','http://purl.org/dc/elements/1.1/',5),
	('dc11','http://purl.org/dc/elements/1.1/',41),
	('dcam','http://purl.org/dc/dcam/',160),
	('dcat','http://www.w3.org/ns/dcat#',120),
	('dce','http://purl.org/dc/elements/1.1/',386),
	('dcite','http://purl.org/spar/datacite/',1189),
	('dcm','http://dcm.com/',1034),
	('dcmit','http://purl.org/dc/dcmitype/',51),
	('dcmitype','http://purl.org/dc/dcmitype/',302),
	('dcn','http://www.w3.org/2007/uwa/context/deliverycontext.owl#',111),
	('dcndl','http://ndl.go.jp/dcndl/terms/',1065),
	('dco','http://info.deepcarbon.net/schema#',633),
	('dcoid','http://dx.deepcarbon.net/',1147),
	('dcq','http://purl.org/dc/qualifiers/1.0/',75),
	('dcr','http://www.isocat.org/ns/dcr.rdf#',777),
	('dcs','http://ontologi.es/doap-changeset#',1434),
	('dct','http://purl.org/dc/terms/',22),
	('dcterm','http://purl.org/dc/terms/',271),
	('dcterms','http://purl.org/dc/terms/',21),
	('dctype','http://purl.org/dc/dcmitype/',206),
	('dctypes','http://purl.org/dc/dcmitype/',876),
	('ddc','http://purl.org/NET/decimalised#',289),
	('ddl','http://purl.org/vocab/riro/ddl#',323),
	('decl','http://www.linkedmodel.org/1.0/schema/decl#',568),
	('defns','http://www.openarchives.org/OAI/2.0/',1248),
	('delta','http://www.w3.org/2004/delta#',1085),
	('deo','http://purl.org/spar/deo/',1082),
	('deps','http://ontologi.es/doap-deps#',1464),
	('derecho','http://purl.org/derecho#',449),
	('dgfoaf','http://west.uni-koblenz.de/ontologies/2010/07/dgfoaf.owl#',511),
	('dgtwc','http://data-gov.tw.rpi.edu/2009/data-gov-twc.rdf#',565),
	('diag','http://www.loc.gov/zing/srw/diagnostic/',1292),
	('dicom','http://purl.org/healthcarevocab/v1#',1408),
	('dir','http://schemas.talis.com/2005/dir/schema#',80),
	('dis','http://stanbol.apache.org/ontology/disambiguation/disambiguation#',927),
	('disco','http://rdf-vocabulary.ddialliance.org/discovery#',726),
	('disease','http://www.agfa.com/w3c/2009/humanDisorder#',652),
	('diseasome','http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/',666),
	('dita','http://purl.org/dita/ns#',582),
	('dive','http://scubadive.networld.to/dive.rdf#',756),
	('dl','http://ontology.ip.rm.cnr.it/ontologies/DOLCE-Lite#',1139),
	('dn','http://purl.org/datanode/ns/',1124),
	('dnb','http://d-nb.info/gnd/',655),
	('dnr','http://www.dotnetrdf.org/configuration#',462),
	('doac','http://ramonantonio.net/doac/0.1/#',247),
	('doap','http://usefulinc.com/ns/doap#',35),
	('doas','http://deductions-software.com/ontologies/doas.owl.ttl#',1445),
	('doc','http://www.w3.org/2000/10/swap/pim/doc#',189),
	('doclist','http://www.junkwork.net/xml/DocumentList#',241),
	('doco','http://purl.org/spar/doco/',1132),
	('dogont','http://elite.polito.it/ontologies/dogont.owl#',1322),
	('dpd','http://www.kanzaki.com/ns/dpd#',1232),
	('dpl','http://dbpedialite.org/things/',796),
	('dq','http://def.seegrid.csiro.au/isotc211/iso19115/2003/dataquality#',1370),
	('dqm','http://purl.org/dqm-vocabulary/v1/dqm#',1104),
	('dr','http://purl.org/swan/2.0/discourse-relationships/',1143),
	('drm','http://vocab.data.gov/def/drm#',1120),
	('drug','http://www.agfa.com/w3c/2009/drugTherapy#',463),
	('drugbank','http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/',117),
	('ds','http://purl.org/ctic/dcat#',1002),
	('dsn','http://purl.org/dsnotify/vocab/eventset/',1446),
	('dso','http://purl.org/ontology/dso#',559),
	('dsp','http://purl.org/metainfo/terms/dsp#',837),
	('dssn','http://purl.org/net/dssn/',786),
	('dt','http://dbpedia.org/datatype/',912),
	('dtype','http://www.linkedmodel.org/schema/dtype#',656),
	('dul','http://www.loa-cnr.it/ontologies/DUL.owl#',353),
	('dummy','http://hello.com/',359),
	('dv','http://rdf.data-vocabulary.org/#',72),
	('dvia','http://data.eurecom.fr/ontology/dvia#',977),
	('dwc','http://rs.tdwg.org/dwc/terms/',610),
	('ean','http://openean.kaufkauf.net/id/',467),
	('earl','http://www.w3.org/ns/earl#',66),
	('eat','http://www.awesomesauce.net/urmom/',575),
	('ebu','http://semantic.eurobau.com/eurobau-utility.owl#',1035),
	('ebucore','http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#',1397),
	('ec','http://eulergui.sourceforge.net/contacts.owl.n3#',1041),
	('ecb','http://ecb.270a.info/class/1.0/',958),
	('ecc','https://ns.eccenca.com/',1401),
	('eco','http://www.ebusiness-unibw.org/ontologies/eclass/5.1.4/#',618),
	('ecos','http://kmm.lboro.ac.uk/ecos/1.0#',1112),
	('ecpo','http://purl.org/ontology/ecpo#',999),
	('ecrm','http://erlangen-crm.org/current/',1201),
	('ecs','http://rdf.ecs.soton.ac.uk/ontology/ecs#',261),
	('edam','http://purl.bioontology.org/ontology/EDAM/',576),
	('edgar','http://edgarwrap.ontologycentral.com/vocab/edgar#',1169),
	('edm','http://www.europeana.eu/schemas/edm/',450),
	('efo','http://www.ebi.ac.uk/efo/',673),
	('eg','http://eulergui.sourceforge.net/engine.owl#',307),
	('ekaw','http://data.semanticweb.org/conference/ekaw/2012/complete/',683),
	('elec','http://purl.org/ctic/sector-publico/elecciones#',1178),
	('elog','http://eulersharp.sourceforge.net/2003/03swap/log-rules#',541),
	('emoca','http://ns.inria.fr/emoca#',1115),
	('emotion','http://ns.inria.fr/emoca#',1096),
	('emp','http://purl.org/ctic/empleo/oferta#',1151),
	('employee','http://www.employee.com/data#',1268),
	('enc','http://www.w3.org/2001/04/xmlenc#',505),
	('ends','http://labs.mondeca.com/vocab/endpointStatus#',846),
	('enhancer','http://stanbol.apache.org/ontology/enhancer/enhancer#',742),
	('ens','http://models.okkam.org/ENS-core-vocabulary.owl#',744),
	('environ','http://eulersharp.sourceforge.net/2003/03swap/environment#',593),
	('ep','http://eprints.org/ontology/',1160),
	('eprints','http://eprints.org/ontology/',501),
	('erce','http://xxefe.de/',1215),
	('ero','http://purl.obolibrary.org/obo/',675),
	('es','http://eulersharp.sourceforge.net/2003/03swap/log-rules#',295),
	('esadm','http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#',1247),
	('esaloj','http://vocab.linkeddata.es/datosabiertos/def/turismo/alojamiento#',1345),
	('escjr','http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero#',1356),
	('esd','http://def.esd.org.uk/',540),
	('eseduc','http://www.purl.org/ontologia/eseduc#',817),
	('estatwrap','http://ontologycentral.com/2009/01/eurostat/ns#',1290),
	('estrn','http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/transporte#',1260),
	('eu','http://eulersharp.sourceforge.net/2003/03swap/log-rules#',483),
	('eui','http://institutions.publicdata.eu/#',839),
	('eumida','http://data.kasabi.com/dataset/eumida/terms/',764),
	('eunis','http://eunis.eea.europa.eu/rdf/species-schema.rdf#',924),
	('eurlex','http://eur-lex.publicdata.eu/ontology/',1226),
	('event','http://purl.org/NET/c4dm/event.owl#',59),
	('events','http://eulersharp.sourceforge.net/2003/03swap/event#',539),
	('evident','http://purl.org/net/evident#',1266),
	('evopat','http://ns.aksw.org/Evolution/',416),
	('evset','http://dsnotify.org/vocab/eventset/0.1/',370),
	('ex','http://example.com/',38),
	('example','http://www.example.org/rdf#',722),
	('exif','http://www.w3.org/2003/12/exif/ns#',199),
	('ext','http://def.seegrid.csiro.au/isotc211/iso19115/2003/extent#',1389),
	('exterms','http://www.example.org/terms/',902),
	('eye','http://jena.hpl.hp.com/Eyeball#',635),
	('ezcontext','http://ontologies.ezweb.morfeo-project.org/ezcontext/ns#',377),
	('eztag','http://ontologies.ezweb.morfeo-project.org/eztag/ns#',267),
	('fab','http://purl.org/fab/ns#',517),
	('fabio','http://purl.org/spar/fabio/',500),
	('factbook','http://www4.wiwiss.fu-berlin.de/factbook/ns#',58),
	('fam','http://vocab.fusepool.info/fam#',1337),
	('fao','http://fao.270a.info/dataset/',1262),
	('fb','http://rdf.freebase.com/ns/',17),
	('fbgeo','http://rdf.freebase.com/ns/location/geocode/',1274),
	('fc','http://www.freeclass.eu/freeclass_v1#',803),
	('fcm','http://eulersharp.sourceforge.net/2006/02swap/fcm#',827),
	('fcp','http://www.newmedialab.at/fcp/',1053),
	('fcs','http://clarin.eu/fcs/resource#',1309),
	('fct','http://openlinksw.com/services/facets/1.0/',739),
	('fd','http://foodable.co/ns/',810),
	('fea','http://vocab.data.gov/def/fea#',1023),
	('fec','http://www.rdfabout.com/rdf/schema/usfec/',230),
	('fed','http://www.openrdf.org/config/sail/federation#',326),
	('fincaselaw','http://purl.org/finlex/schema/oikeus/',1032),
	('fingal','http://vocab.deri.ie/fingal#',741),
	('finlaw','http://purl.org/finlex/schema/laki/',966),
	('fise','http://fise.iks-project.eu/ontology/',650),
	('fl','http://eulersharp.sourceforge.net/2003/03swap/fl-rules#',808),
	('flow','http://www.w3.org/2005/01/wf/flow#',748),
	('fls','http://lukasblaho.sk/football_league_schema#',798),
	('fma','http://sig.uw.edu/fma#',1355),
	('fn','http://www.w3.org/2005/xpath-functions#',77),
	('foaf','http://xmlns.com/foaf/0.1/',3),
	('food','http://purl.org/foodontology#',426),
	('form','http://deductions-software.com/ontologies/forms.owl.ttl#',1366),
	('formats','http://www.w3.org/ns/formats/',278),
	('fos','http://futurios.org/fos/spec/',952),
	('fowl','http://www.w3.org/TR/2003/PR-owl-guide-20031209/food#',641),
	('fp3','http://vocab.fusepool.info/fp3#',1287),
	('frad','http://iflastandards.info/ns/fr/frad/',863),
	('frapo','http://purl.org/cerif/frapo/',919),
	('frb','http://frb.270a.info/dataset/',1293),
	('frbr','http://purl.org/vocab/frbr/core#',122),
	('frbrcore','http://purl.org/vocab/frbr/core#',755),
	('frbre','http://purl.org/vocab/frbr/extended#',318),
	('frbrer','http://iflastandards.info/ns/fr/frbr/frbrer/',988),
	('freebase','http://rdf.freebase.com/ns/',434),
	('fresnel','http://www.w3.org/2004/09/fresnel#',191),
	('friends','http://www.openarchives.org/OAI/2.0/friends/',1270),
	('frir','http://purl.org/twc/ontology/frir.owl#',816),
	('frsad','http://iflastandards.info/ns/fr/frsad/',985),
	('ftcontent','http://www.ft.com/ontology/content/',1222),
	('func','http://www.w3.org/2007/rif-builtin-function#',713),
	('gadm','http://gadm.geovocab.org/ontology#',1185),
	('gaf','http://groundedannotationframework.org/',1237),
	('galaksiya','http://ontoloji.galaksiya.com/vocab/',1385),
	('game','http://data.totl.net/game/',403),
	('gastro','http://www.ebsemantics.net/gastro#',1158),
	('gawd','http://gawd.atlantides.org/terms/',909),
	('gazetteer','http://data.ordnancesurvey.co.uk/ontology/50kGazetteer/',703),
	('gbv','http://purl.org/ontology/gbv/',802),
	('gc','http://www.oegov.org/core/owl/gc#',598),
	('gcis','http://data.globalchange.gov/gcis.owl#',1214),
	('gd','http://rdf.data-vocabulary.org/#',306),
	('gelo','http://krauthammerlab.med.yale.edu/ontologies/gelo#',585),
	('gen','http://www.w3.org/2006/gen/ont#',44),
	('genab','http://eulersharp.sourceforge.net/2003/03swap/genomeAbnormality#',534),
	('genea','http://www.owl-ontologies.com/generations.owl#',815),
	('geo','http://www.w3.org/2003/01/geo/wgs84_pos#',13),
	('geocontext','http://www.geocontext.org/publ/2013/vocab#',983),
	('geod','http://vocab.lenka.no/geo-deling#',1102),
	('geodata','http://sws.geonames.org/',514),
	('geoes','http://geo.linkeddata.es/ontology/',208),
	('geof','http://www.opengis.net/def/function/geosparql/',926),
	('geofla','http://data.ign.fr/ontologies/geofla#',943),
	('geographis','http://telegraphis.net/ontology/geography/geography#',367),
	('geom','http://geovocab.org/geometry#',763),
	('geonames','http://www.geonames.org/ontology#',18),
	('geop','http://aims.fao.org/aos/geopolitical.owl#',1217),
	('georss','http://www.georss.org/georss/',556),
	('geos','http://www.telegraphis.net/ontology/geography/geography#',1358),
	('geosp','http://rdf.geospecies.org/ont/geospecies#',1153),
	('geosparql','http://www.opengis.net/ont/geosparql#',1307),
	('geospecies','http://rdf.geospecies.org/ont/geospecies#',425),
	('geovocab','http://geovocab.org/',880),
	('geovoid','http://purl.org/geovocamp/ontology/geovoid/',1348),
	('germplasm','http://purl.org/germplasm/terms#',770),
	('gesis','http://lod.gesis.org/lodpilot/ALLBUS/vocab.rdf#',857),
	('gf','http://def.seegrid.csiro.au/isotc211/iso19109/2005/feature#',1387),
	('gfo','http://www.onto-med.de/ontologies/gfo.owl#',969),
	('giving','http://ontologi.es/giving#',109),
	('gldp','http://www.w3.org/ns/people#',14),
	('gm','http://def.seegrid.csiro.au/isotc211/iso19107/2003/geometry#',1419),
	('gml','http://www.opengis.net/ont/gml#',469),
	('gn','http://www.geonames.org/ontology#',171),
	('gnd','http://d-nb.info/standards/elementset/gnd#',518),
	('gndo','http://d-nb.info/standards/elementset/gnd#',1008),
	('gnm','http://www.geonames.org/ontology/mappings/',1191),
	('gnvc','http://purl.org/gc/',1093),
	('go','http://www.geneontology.org/go#',286),
	('gob','http://purl.org/ontology/last-fm/',342),
	('goef','http://purl.org/twc/vocab/goef#',819),
	('gold','http://purl.org/linguistics/gold/',316),
	('govtrackus','http://www.rdfabout.com/rdf/usgov/geo/us/',709),
	('govwild','http://govwild.org/0.6/GWOntology.rdf/',522),
	('gpml','http://vocabularies.wikipathways.org/gpml#',1427),
	('gpt','http://purl.org/vocab/riro/gpt#',314),
	('gq','http://genomequest.com/',1087),
	('gr','http://purl.org/goodrelations/v1#',20),
	('graffle','http://purl.org/twc/vocab/vsr/graffle#',1063),
	('granatum','http://chem.deri.ie/granatum/',143),
	('graves','http://rdf.muninn-project.org/ontologies/graves#',1163),
	('grddl','http://www.w3.org/2003/g/data-view#',255),
	('greg','http://kasei.us/about/foaf.xrdf#',706),
	('gridworks','http://purl.org/net/opmv/types/gridworks#',489),
	('grs','http://www.georss.org/georss/',794),
	('gso','http://www.w3.org/2006/gen/ont#',639),
	('gsp','http://www.opengis.net/ont/geosparql#',619),
	('gtfs','http://vocab.gtfs.org/terms#',1380),
	('gts','http://resource.geosciml.org/ontology/timescale/gts#',1407),
	('gv','http://rdf.data-vocabulary.org/#',488),
	('gvp','http://vocab.getty.edu/ontology#',1183),
	('gxa','http://www.ebi.ac.uk/gxa/',809),
	('h2o','http://def.seegrid.csiro.au/isotc211/iso19150/-2/2012/basic#',1422),
	('h5','http://buzzword.org.uk/rdf/h5#',263),
	('hard','http://www.w3.org/2007/uwa/context/hardware.owl#',266),
	('harrisons','http://harrisons.cc/',996),
	('hartigprov','http://purl.org/net/provenance/ns#',623),
	('hcard','http://purl.org/uF/hCard/terms/',714),
	('hcterms','http://purl.org/uF/hCard/terms/',262),
	('hdo','http://www.samos.gr/ontologies/helpdeskOnto.owl#',1398),
	('health','http://purl.org/twc/health/vocab/',684),
	('healthcare','http://www.agfa.com/w3c/2009/healthCare#',496),
	('hemogram','http://www.agfa.com/w3c/2009/hemogram#',564),
	('hg','http://www.holygoat.co.uk/owl/redwood/0.1/tags/',800),
	('hgnc','http://bio2rdf.org/hgnc:',832),
	('hifm','http://purl.org/net/hifm/data#',910),
	('hints2005','http://purl.org/twc/cabig/model/HINTS2005-1.owl#',604),
	('hlisting','http://sindice.com/hlisting/0.1/',264),
	('hlygt','http://www.holygoat.co.uk/owl/redwood/0.1/tags/',1107),
	('holding','http://purl.org/ontology/holding#',1341),
	('hospital','http://www.agfa.com/w3c/2009/hospital#',574),
	('hp','http://pictogram.tokyo/vocabulary#',1461),
	('hr','http://iserve.kmi.open.ac.uk/ns/hrests#',1413),
	('htir','http://www.w3.org/2011/http#',659),
	('http','http://www.w3.org/2011/http#',39),
	('httph','http://www.w3.org/2007/ont/httph#',446),
	('httpm','http://www.w3.org/2011/http-methods#',975),
	('httpvoc','http://www.w3.org/2006/http#',725),
	('human','http://eulersharp.sourceforge.net/2003/03swap/human#',509),
	('humanbody','http://eulersharp.sourceforge.net/2003/03swap/humanBody#',548),
	('hxl','http://hxl.humanitarianresponse.info/ns/#',818),
	('hydra','http://www.w3.org/ns/hydra/core#',771),
	('iao','http://purl.obolibrary.org/obo/iao.owl#',753),
	('ibis','http://purl.org/ibis#',245),
	('ic','http://imi.ipa.go.jp/ns/core/210#',1437),
	('ical','http://www.w3.org/2002/12/cal/ical#',62),
	('icaltzd','http://www.w3.org/2002/12/cal/icaltzd#',557),
	('icane','http://www.icane.es/opendata/vocab#',1084),
	('idemo','http://rdf.insee.fr/def/demo#',581),
	('identity','http://purl.org/twc/ontologies/identity.owl#',778),
	('igeo','http://rdf.insee.fr/def/geo#',665),
	('ignf','http://data.ign.fr/def/ignf#',1444),
	('ilap','http://data.posccaesar.org/ilap/',1360),
	('imf','http://imf.270a.info/dataset/',1334),
	('imm','http://schemas.microsoft.com/imm/',233),
	('imreg','http://www.w3.org/2004/02/image-regions#',348),
	('infection','http://www.agfa.com/w3c/2009/infectiousDisorder#',733),
	('infor','http://www.ontologydesignpatterns.org/cp/owl/informationrealization.owl#',1077),
	('infosys','http://www.infosys.com/',830),
	('inno','http://purl.org/innovation/ns#',1076),
	('interval','http://reference.data.gov.uk/def/intervals/',537),
	('intervals','http://reference.data.gov.uk/def/intervals/',799),
	('iol','http://www.ontologydesignpatterns.org/ont/dul/IOLite.owl#',1144),
	('iot','http://www.linkedthings.com/iot/',1080),
	('ipad','http://www.padinthecity.com/',779),
	('ir','http://www.ontologydesignpatterns.org/cp/owl/informationrealization.owl#',92),
	('ire','http://www.ontologydesignpatterns.org/cpont/ire.owl#',337),
	('iron','http://purl.org/ontology/iron#',695),
	('irrl','http://www.ontologydesignpatterns.org/cp/owl/informationobjectsandrepresentationlanguages.owl#',188),
	('irstea','http://ontology.irstea.fr/',1310),
	('irsteaont','http://ontology.irstea.fr/weather/ontology#',1313),
	('irw','http://www.ontologydesignpatterns.org/ont/web/irw.owl#',177),
	('is','http://purl.org/ontology/is/core#',482),
	('isbd','http://iflastandards.info/ns/isbd/elements/',397),
	('isi','http://purl.org/ontology/is/inst/',409),
	('iso','http://purl.org/iso25964/skos-thes#',787),
	('isocat','http://www.isocat.org/datcat/',1388),
	('isothes','http://purl.org/iso25964/skos-thes#',806),
	('isq','http://purl.org/ontology/is/quality/',424),
	('ist','http://purl.org/ontology/is/types/',431),
	('iswc','http://annotation.semanticweb.org/2004/iswc#',211),
	('italy','http://data.kasabi.com/dataset/italy/schema/',956),
	('itm','http://spi-fm.uca.es/spdef/models/genericTools/itm/1.0#',1443),
	('itsmo','http://ontology.it/itsmo/v1#',1159),
	('itsrdf','http://www.w3.org/2005/11/its/rdf#',758),
	('java','http://www.w3.org/2007/uwa/context/java.owl#',182),
	('jdbc','http://d2rq.org/terms/jdbc/',114),
	('jita','http://aims.fao.org/aos/jita/',728),
	('jjd','http://www.joshuajeeson.com/',905),
	('jp1','http://rdf.muninn-project.org/ontologies/jp1/',1303),
	('kai','http://kai.uni-kiel.de/',1207),
	('kb','http://deductions.sf.net/ontology/knowledge_base.owl#',276),
	('kbp','http://tackbp.org/2013/ontology#',1040),
	('kdo','http://kdo.render-project.eu/kdo#',692),
	('kegg','http://bio2rdf.org/ns/kegg#',1449),
	('keys','http://purl.org/NET/c4dm/keys.owl#',1420),
	('kml','http://www.opengis.net/kml/2.2#',1276),
	('koly','http://www.ensias.ma/',1263),
	('kontakt','http://richard.cyganiak.de/',767),
	('kupkb','http://www.e-lico.eu/data/kupkb/',752),
	('kw','http://kwantu.net/kw/',670),
	('kwijibo','http://kwijibo.talis.com/',246),
	('l2sp','http://www.linked2safety-project.eu/properties/',1298),
	('l4a','http://labels4all.info/ns/',751),
	('l4lod','http://ns.inria.fr/l4lod/v2/',950),
	('laabs','http://dbpedia.org/resource/',1197),
	('label','http://purl.org/net/vocab/2004/03/label#',213),
	('lang','http://ontologi.es/lang/core#',250),
	('language','http://id.loc.gov/vocabulary/iso639-1/',1250),
	('languages','http://eulersharp.sourceforge.net/2003/03swap/languages#',487),
	('laposte','http://data.lirmm.fr/ontologies/laposte#',868),
	('lark1','http://users.utcluj.ro/~raluca/ontology/Ontology1279614123500.owl#',411),
	('lastfm','http://purl.org/ontology/last-fm/',235),
	('lc','http://www.linkedcode.org/2014/12/linkedcode#',1458),
	('lctr','http://data.linkedct.org/vocab/resource/',734),
	('lcy','http://purl.org/vocab/lifecycle/schema#',1078),
	('lda','http://purl.org/linked-data/api/vocab#',1243),
	('ldap','http://purl.org/net/ldap/',396),
	('ldp','http://www.w3.org/ns/ldp#',527),
	('ldr','http://purl.oclc.org/NET/ldr/ns#',1433),
	('lemon','http://lemon-model.net/lemon#',549),
	('lemonuby','http://lemon-model.net/lexica/uby/',1450),
	('lex','http://purl.org/lex#',833),
	('lexcz','http://purl.org/lex/cz#',1125),
	('lexicon','http://www.example.org/lexicon#',1251),
	('lexinfo','http://www.lexinfo.net/ontology/2.0/lexinfo#',1220),
	('lexvo','http://lexvo.org/ontology#',862),
	('lfm','http://purl.org/ontology/last-fm/',190),
	('lfn','http://www.dotnetrdf.org/leviathan#',280),
	('lfov','https://w3id.org/legal_form#',1236),
	('lgd','http://linkedgeodata.org/vocabulary#',196),
	('lgdo','http://linkedgeodata.org/ontology/',498),
	('lgv','http://linkedgeodata.org/ontology/',835),
	('lh','http://vocab.inf.ed.ac.uk/library/holdings#',979),
	('li','http://def.seegrid.csiro.au/isotc211/iso19115/2003/lineage#',1233),
	('lib','http://purl.org/library/',603),
	('library','http://purl.org/library/',502),
	('life','http://life.deri.ie/schema/',761),
	('lifecycle','http://purl.org/vocab/lifecycle/schema#',257),
	('like','http://ontologi.es/like#',309),
	('lime','http://art.uniroma2.it/ontologies/lime#',1241),
	('limo','http://www.purl.org/limo-ontology/limo#',1436),
	('limoo','http://purl.org/LiMo/0.1/',1109),
	('ling','http://purl.org/voc/ling/',1188),
	('lingvo','http://www.lingvoj.org/ontology#',1175),
	('lingvoj','http://www.lingvoj.org/ontology#',195),
	('link','http://www.w3.org/2006/link#',148),
	('linkedct','http://data.linkedct.org/vocab/',466),
	('linkedmdb','http://data.linkedmdb.org/sparql/',536),
	('lio','http://purl.org/net/lio#',1447),
	('list','http://www.w3.org/2000/10/swap/list#',344),
	('ll','http://lodlaundromat.org/resource/',1314),
	('lldr','http://purl.oclc.org/NET/lldr/ns#',940),
	('llm','http://lodlaundromat.org/metrics/ontology/',1382),
	('llo','http://lodlaundromat.org/ontology/',1323),
	('lmf','http://www.lexinfo.net/lmf#',1369),
	('lmm1','http://www.ontologydesignpatterns.org/ont/lmm/LMM_L1.owl#',1123),
	('lmm2','http://www.ontologydesignpatterns.org/ont/lmm/LMM_L2.owl#',1127),
	('loc','http://www.w3.org/2007/uwa/context/location.owl#',136),
	('locah','http://data.archiveshub.ac.uk/def/',1415),
	('location','http://sw.deri.org/2006/07/location/loc#',1227),
	('locn','http://www.w3.org/ns/locn#',1203),
	('locwd','http://purl.org/locwd/schema#',984),
	('lod2','http://lod2.eu/schema/',589),
	('lodac','http://lod.ac/ns/lodac#',731),
	('lode','http://linkedevents.org/ontology/',156),
	('lofv','http://purl.org/legal_form/vocab#',1299),
	('log','http://www.w3.org/2000/10/swap/log#',71),
	('lom','http://ltsc.ieee.org/rdf/lomv1p0/lom#',293),
	('lomvoc','http://ltsc.ieee.org/rdf/lomv1p0/vocabulary#',112),
	('loted','http://loted.eu/ontology#',1440),
	('lotico','http://www.lotico.com/resource/',243),
	('loticoowl','http://www.lotico.com/ontology/',475),
	('lp','http://launchpad.net/rdf/launchpad#',497),
	('lpeu','http://purl.org/linkedpolitics/vocabulary/eu/plenary/',1435),
	('lr','http://linkedrecipes.org/schema/',844),
	('ls','http://linkedspending.aksw.org/instance/',1383),
	('lsc','http://linkedscience.org/lsc/ns#',1146),
	('lso','http://linkedspending.aksw.org/ontology/',1425),
	('lt','http://diplomski.nelakolundzija.org/LTontology.rdf#',329),
	('ludo','http://vocab.ox.ac.uk/ludo#',1062),
	('lv','http://purl.org/lobid/lv#',346),
	('lvont','http://lexvo.org/ontology#',472),
	('lx','http://purl.org/NET/lx#',221),
	('lyou','http://purl.org/linkingyou/',586),
	('ma','http://www.w3.org/ns/ma-ont#',380),
	('mads','http://www.loc.gov/mads/rdf/v1#',1074),
	('madsrdf','http://www.loc.gov/mads/rdf/v1#',363),
	('malignneo','http://www.agfa.com/w3c/2009/malignantNeoplasm#',550),
	('mammal','http://lod.taxonconcept.org/ontology/p01/Mammalia/index.owl#',1256),
	('marcrel','http://id.loc.gov/vocabulary/relators/',167),
	('marl','http://www.gsi.dit.upm.es/ontologies/marl/ns#',643),
	('marshall','http://sites.google.com/site/xgmaitc/',759),
	('maso','http://securitytoolbox.appspot.com/MASO#',1428),
	('math','http://www.w3.org/2000/10/swap/math#',107),
	('mb','http://dbtune.org/musicbrainz/resource/instrument/',1275),
	('md','http://www.w3.org/ns/md#',32),
	('mds','http://doc.metalex.eu/id/',1136),
	('meb','http://rdf.myexperiment.org/ontologies/base/',1130),
	('media','http://purl.org/microformat/hmedia/',65),
	('meetup','http://www.lotico.com/meetup/',279),
	('mei','http://www.music-encoding.org/ns/mei/',682),
	('memo','http://ontologies.smile.deri.ie/2009/02/27/memo#',100),
	('meta','http://www.openrdf.org/rdf/2009/metadata#',227),
	('metadata','http://purl.oreilly.com/ns/meta/',1246),
	('metalex','http://www.metalex.eu/schema/1.0#',554),
	('meteo','http://purl.org/ns/meteo#',325),
	('mf','http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#',387),
	('mged','http://mged.sourceforge.net/ontologies/MGEDOntology.owl#',1119),
	('mico','http://www.mico-project.eu/ns/platform/1.0/schema#',1421),
	('mil','http://rdf.muninn-project.org/ontologies/military#',973),
	('mime','http://purl.org/NET/mediatypes/',962),
	('mit','http://purl.org/ontology/mo/mit#',168),
	('mm','http://linkedmultimedia.org/sparql-mm/functions#',1212),
	('mmd','http://musicbrainz.org/ns/mmd-1.0#',1452),
	('mmf','http://linkedmultimedia.org/sparql-mm/ns/1.0.0/function#',1423),
	('mmt','http://linkedmultimedia.org/sparql-mm/functions/temporal#',1284),
	('mo','http://purl.org/ontology/mo/',47),
	('moac','http://observedchange.com/moac/ns#',1135),
	('moat','http://moat-project.org/ns#',224),
	('moby','http://www.mygrid.org.uk/mygrid-moby-service#',847),
	('mocanal','http://www.semanticweb.org/asow/ontologies/2013/9/untitled-ontology-36#',1129),
	('mods','http://www.loc.gov/mods/v3#',884),
	('mohammad','http://manesht.ir/',897),
	('money','http://purl.org/net/rdf-money/',287),
	('movie','http://data.linkedmdb.org/resource/movie/',129),
	('mp','http://jicamaro.info/mp#',1091),
	('mpeg7','http://rhizomik.net/ontologies/2005/03/Mpeg7-2001.owl#',638),
	('mrel','http://id.loc.gov/vocabulary/relators/',1057),
	('ms','http://purl.org/obo/owl/MS#',793),
	('msm','http://iserve.kmi.open.ac.uk/ns/msm#',1317),
	('msr','http://www.telegraphis.net/ontology/measurement/measurement#',1181),
	('mt','http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#',1210),
	('mte','http://nl.ijs.si/ME/owl/',781),
	('mtecore','http://purl.org/olia/mte/multext-east.owl#',701),
	('mu','http://www.kanzaki.com/ns/music#',101),
	('muldicat','http://iflastandards.info/ns/muldicat#',1118),
	('muni','http://vocab.linkeddata.es/urbanismo-infraestructuras/territorio#',671),
	('muo','http://purl.oclc.org/NET/muo/muo#',492),
	('music','http://musicontology.com/',144),
	('musim','http://purl.org/ontology/similarity/',78),
	('muto','http://purl.org/muto/core#',494),
	('mvco','http://purl.oclc.org/NET/mvco.owl#',1133),
	('my','http://www.mobile.com/model/',1240),
	('mygrid','http://www.mygrid.org.uk/ontology#',555),
	('myprefix','http://myprefix.org/',773),
	('myspace','http://purl.org/ontology/myspace#',115),
	('myspo','http://purl.org/ontology/myspace#',268),
	('mysql','http://web-semantics.org/ns/mysql/',299),
	('name','http://example.org/name#',614),
	('namespaces','https://vg.no/',1060),
	('nao','http://www.semanticdesktop.org/ontologies/2007/08/15/nao#',181),
	('naval','http://rdf.muninn-project.org/ontologies/naval#',1291),
	('navm','https://w3id.org/navigation_menu#',1273),
	('ncal','http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#',251),
	('ncbitaxon','http://purl.org/obo/owl/NCBITaxon#',871),
	('nco','http://www.semanticdesktop.org/ontologies/2007/03/22/nco#',186),
	('ndl','http://schemas.ogf.org/nml/2013/05/base#',1230),
	('ne','http://umbel.org/umbel/ne/',223),
	('nerd','http://nerd.eurecom.fr/ontology#',1359),
	('net','http://www.w3.org/2007/uwa/context/network.owl#',296),
	('nexif','http://www.semanticdesktop.org/ontologies/2007/05/10/nexif#',252),
	('nfo','http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#',127),
	('ngeo','http://geovocab.org/geometry#',573),
	('ngeoi','http://vocab.lenka.no/geo-deling#',676),
	('nid3','http://www.semanticdesktop.org/ontologies/2007/05/10/nid3#',333),
	('nidm','http://nidm.nidash.org/',1097),
	('nie','http://www.semanticdesktop.org/ontologies/2007/01/19/nie#',46),
	('nif','http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#',608),
	('nmo','http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#',260),
	('nndsr','http://semanticdiet.com/schema/usda/nndsr/',542),
	('no','http://km.aifb.kit.edu/projects/numbers/number#',698),
	('nocal','http://vocab.deri.ie/nocal#',507),
	('np','http://www.nanopub.org/nschema#',824),
	('npdv','http://sws.ifi.uio.no/vocab/npd#',1432),
	('npg','http://ns.nature.com/terms/',609),
	('npgd','http://ns.nature.com/datasets/',870),
	('npgg','http://ns.nature.com/graphs/',859),
	('npgx','http://ns.nature.com/extensions/',776),
	('nrl','http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#',219),
	('nsa','http://multimedialab.elis.ugent.be/organon/ontologies/ninsuna#',465),
	('nsl','http://purl.org/ontology/storyline/',974),
	('nsogi','http://prefix.cc/nsogi:',215),
	('nt','http://ns.inria.fr/nicetag/2010/09/09/voc#',474),
	('ntag','http://ns.inria.fr/nicetag/2010/09/09/voc#',1103),
	('nuts','http://nuts.psi.enakting.org/id/BE335/doc/',904),
	('nxp','http://purl.org/nxp/schema/v1/',750),
	('nxs','http://www.neclimateus.org/',1295),
	('nyt','http://data.nytimes.com/',1064),
	('nytimes','http://data.nytimes.com/elements/',745),
	('oa','http://www.w3.org/ns/oa#',430),
	('oac','http://www.openannotation.org/ns/',688),
	('oad','http://lod.xdams.org/reload/oad/',1460),
	('oan','http://data.lirmm.fr/ontologies/oan/',1390),
	('oarj','http://opendepot.org/reference/linked/1.0/',898),
	('oat','http://openlinksw.com/schemas/oat/',347),
	('oauth','http://demiblog.org/vocab/oauth#',162),
	('oax','http://www.w3.org/ns/openannotation/extensions/',743),
	('obj','http://www.openrdf.org/rdf/2009/object#',331),
	('obo','http://purl.obolibrary.org/obo/',621),
	('oboe','http://ecoinformatics.org/oboe/oboe.1.0/oboe-core.owl#',680),
	('oboro','http://obofoundry.org/ro/ro.owl#',455),
	('oboso','http://purl.org/obo/owl/SO#',687),
	('obsm','http://rdf.geospecies.org/methods/observationMethod#',1171),
	('oc','http://opencoinage.org/rdf/',356),
	('occult','http://data.totl.net/occult/',994),
	('ocd','http://dati.camera.it/ocd/',601),
	('od','http://purl.org/twc/vocab/opendap#',1218),
	('odapp','http://vocab.deri.ie/odapp#',1155),
	('odapps','http://semweb.mmlab.be/ns/odapps#',1308),
	('odcs','http://opendata.cz/infrastructure/odcleanstore/',1009),
	('odo','http://ocean-data.org/schema/',1454),
	('odp','http://ontologydesignpatterns.org/',520),
	('odpart','http://www.ontologydesignpatterns.org/cp/owl/participation.owl#',1193),
	('odrl','http://www.w3.org/ns/odrl/2/',1267),
	('odrs','http://schema.theodi.org/odrs#',1456),
	('odv','http://reference.data.gov.uk/def/organogram/',1141),
	('oecc','http://www.oegov.org/core/owl/cc#',1149),
	('oecd','http://oecd.270a.info/dataset/',942),
	('of','http://owlrep.eu01.aws.af.cm/fridge#',1311),
	('og','http://opengraphprotocol.org/schema/',57),
	('ogbd','http://www.ogbd.fr/2012/ontologie#',1052),
	('ogorg','http://opengraph.org/schema/',889),
	('ogp','http://ogp.me/ns#',647),
	('oh','http://semweb.mmlab.be/ns/oh#',1294),
	('oils','http://lemon-model.net/oils#',1372),
	('oj','http://ontojob.at/',998),
	('ok','http://okkam.org/terms#',104),
	('okg','http://openknowledgegraph.org/ontology/',700),
	('okkam','http://models.okkam.org/ENS-core-vocabulary#',369),
	('olac','http://www.language-archives.org/OLAC/1.0/',1283),
	('olac11','http://www.language-archives.org/OLAC/1.1/',1278),
	('olad','http://openlad.org/vocab#',1061),
	('olca','http://www.lingvoj.org/olca#',1457),
	('olia','http://purl.org/olia/olia.owl#',663),
	('oliasystem','http://purl.org/olia/system.owl#',1101),
	('olo','http://purl.org/ontology/olo/core#',421),
	('om','http://opendata.caceres.es/def/ontomunicipio#',1173),
	('omapi','http://purl.org/omapi/0.2/#',893),
	('omb','http://purl.org/ontomedia/ext/common/being#',187),
	('omc','http://purl.org/ontomedia/ext/common/bestiary#',275),
	('omdoc','http://omdoc.org/ontology/',1282),
	('ome','http://purl.org/ontomedia/core/expression#',88),
	('omm','http://purl.org/ontomedia/core/media#',321),
	('omn','http://www.openmobilenetwork.org/resource/',967),
	('omp','http://purl.org/ontomedia/ext/common/profession#',226),
	('omt','http://purl.org/ontomedia/ext/common/trait#',173),
	('omv','http://omv.ontoware.org/2005/05/ontology#',762),
	('onisep','http://rdf.onisep.fr/resource/',1280),
	('onssprel','http://www.ordnancesurvey.co.uk/ontology/SpatialRelations/v0.2/SpatialRelations.owl#',941),
	('ont','http://purl.org/net/ns/ontology-annot#',8),
	('onto','http://www.ontotext.com/',10),
	('ontopic','http://www.ontologydesignpatterns.org/ont/dul/ontopic.owl#',1138),
	('ontosec','http://www.semanticweb.org/ontologies/2008/11/OntologySecurity.owl#',1465),
	('onyx','http://www.gsi.dit.upm.es/ontologies/onyx/ns#',1157),
	('oo','http://purl.org/openorg/',118),
	('op','http://environment.data.gov.au/def/op#',1206),
	('open','http://open.vocab.org/terms/',838),
	('opencyc','http://sw.opencyc.org/concept/',1213),
	('opengov','http://www.w3.org/opengov#',1467),
	('openlinks','http://www.openlinksw.com/schemas/virtrdf#',532),
	('opensearch','http://a9.com/-/spec/opensearch/1.1/',374),
	('openskos','http://openskos.org/xmlns#',1296),
	('oper','http://sweet.jpl.nasa.gov/2.0/mathOperation.owl#',727),
	('opl','http://openlinksw.com/schema/attribution#',1006),
	('oplacl','http://www.openlinksw.com/ontology/acl#',1320),
	('oplcb','http://www.openlinksw.com/schemas/crunchbase#',1417),
	('oplcert','http://www.openlinksw.com/schemas/cert#',1438),
	('oplecrm','http://www.openlinksw.com/ontology/ecrm#',1463),
	('opllic','http://www.openlinksw.com/ontology/licenses#',1343),
	('oplmkt','http://www.openlinksw.com/ontology/market#',1453),
	('oplprod','http://www.openlinksw.com/ontology/products#',1362),
	('oplres','http://www.openlinksw.com/ontology/restrictions#',1347),
	('opm','http://openprovenance.org/ontology#',242),
	('opmo','http://openprovenance.org/model/opmo#',1177),
	('opmv','http://purl.org/net/opmv/ns#',460),
	('opmw','http://www.opmw.org/ontology/',851),
	('opo','http://online-presence.net/opo/ns#',365),
	('oprovo','http://openprovenance.org/ontology#',1162),
	('opus','http://lsdis.cs.uga.edu/projects/semdis/opus#',422),
	('opwn','http://www.ontologyportal.org/WordNet.owl#',523),
	('orca','http://geni-orca.renci.org/owl/topology.owl#',821),
	('ordf','http://purl.org/NET/ordf/',1176),
	('ore','http://www.openarchives.org/ore/terms/',152),
	('org','http://www.w3.org/ns/org#',27),
	('organism','http://eulersharp.sourceforge.net/2003/03swap/organism#',477),
	('organiz','http://eulersharp.sourceforge.net/2003/03swap/organization#',484),
	('origins','http://origins.link/',1269),
	('os','http://www.w3.org/2000/10/swap/os#',220),
	('osadm','http://data.ordnancesurvey.co.uk/ontology/admingeo/',1100),
	('osag','http://www.ordnancesurvey.co.uk/ontology/AdministrativeGeography/v2.0/AdministrativeGeography.rdf#',84),
	('osgb','http://data.ordnancesurvey.co.uk/id/',272),
	('osgeom','http://data.ordnancesurvey.co.uk/ontology/geometry/',1121),
	('oslc','http://open-services.net/ns/core#',826),
	('oslo','http://purl.org/oslo/ns/localgov#',1441),
	('osmsemnet','http://spatial.ucd.ie/2012/08/osmsemnet/',797),
	('osn','http://spatial.ucd.ie/lod/osn/',736),
	('osoc','http://web-semantics.org/ns/opensocial#',320),
	('osp','http://data.lirmm.fr/ontologies/osp#',867),
	('ospost','http://data.ordnancesurvey.co.uk/ontology/postcode/',719),
	('osr','http://dati.senato.it/osr/',1031),
	('oss','http://opendata.caceres.es/def/ontosemanasanta#',1459),
	('osspr','http://data.ordnancesurvey.co.uk/ontology/spatialrelations/',1048),
	('ostop','http://www.ordnancesurvey.co.uk/ontology/Topography/v0.1/Topography.owl#',1142),
	('osukdt','http://www.ordnancesurvey.co.uk/ontology/Datatypes.owl#',920),
	('out','http://ontologies.hypios.com/out#',664),
	('ov','http://open.vocab.org/terms/',134),
	('overheid','http://standaarden.overheid.nl/owms/',853),
	('owl','http://www.w3.org/2002/07/owl#',6),
	('owlim','http://www.ontotext.com/trree/owlim#',106),
	('owls','http://www.daml.org/services/owl-s/1.2/Service.owl#',644),
	('owlse','http://www.daml.org/services/owl-s/1.2/generic/Expression.owl#',899),
	('owltime','http://www.w3.org/TR/owl-time#',696),
	('ox','http://vocab.ox.ac.uk/projectfunding#',1131),
	('p20','http://zbw.eu/beta/p20/vocab/',636),
	('p3p','http://www.w3.org/2002/01/p3prdfv1#',253),
	('paia','http://purl.org/ontology/paia#',1098),
	('pam','http://prismstandard.org/namespaces/pam/2.0/',959),
	('parl','http://reference.data.gov.uk/def/parliament/',1393),
	('part','http://purl.org/vocab/participation/schema#',1070),
	('particip','http://purl.org/vocab/participation/schema#',1072),
	('passim','http://data.lirmm.fr/ontologies/passim#',1164),
	('pat','http://purl.org/hpi/patchr#',840),
	('pattern','http://www.essepuntato.it/2008/12/pattern#',1403),
	('pav','http://purl.org/pav/',704),
	('pay','http://purl.org/commerce/payment#',795),
	('payment','http://reference.data.gov.uk/def/payment#',525),
	('pbo','http://purl.org/ontology/pbo/core#',479),
	('pc','http://purl.org/procurement/public-contracts#',119),
	('pccz','http://purl.org/procurement/public-contracts-czech#',740),
	('pco','http://purl.org/procurement/public-contracts#',1271),
	('pdo','http://ontologies.smile.deri.ie/pdo#',439),
	('penis','http://penis.to/#',1108),
	('penn','http://purl.org/olia/penn.owl#',947),
	('person','http://www.w3.org/ns/person#',651),
	('pext','http://www.ontotext.com/proton/protonext#',1028),
	('pf','http://jena.hpl.hp.com/ARQ/property#',678),
	('pgterms','http://www.gutenberg.org/2009/pgterms/',442),
	('phil','http://philosurfical.open.ac.uk/ontology/philosurfical.owl/',515),
	('photoshop','http://ns.adobe.com/photoshop/1.0/',934),
	('phss','http://ns.poundhill.com/phss/1.0/',282),
	('physo','http://merlin.phys.uni.lodz.pl/onto/physo/physo.owl#',1339),
	('pic','http://www.ipaw.info/ns/picaso#',1304),
	('pimo','http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#',399),
	('ping','http://purl.org/net/pingback/',301),
	('pingback','http://purl.org/net/pingback/',937),
	('pizza','http://www.co-ode.org/ontologies/pizza/pizza.owl#',1033),
	('pkgsrc','http://pkgsrc.co/schema#',1039),
	('pkm','http://www.ontotext.com/proton/protonkm#',1338),
	('pkmn','http://pokedex.dataincubator.org/pkm/',882),
	('place','http://purl.org/ontology/places/',715),
	('places','http://purl.org/ontology/places#',524),
	('play','http://uriplay.org/spec/ontology/#',384),
	('ple','http://pleiades.stoa.org/places/',854),
	('plink','http://buzzword.org.uk/rdf/personal-link-types#',372),
	('plo','http://purl.org/net/po#',1349),
	('pml','http://provenanceweb.org/ns/pml#',584),
	('pmlj','http://inference-web.org/2.0/pml-justification.owl#',140),
	('pmlp','http://inference-web.org/2.0/pml-provenance.owl#',231),
	('pmlr','http://inference-web.org/2.0/pml-relation.owl#',350),
	('pmlt','http://inference-web.org/2.0/pml-trust.owl#',464),
	('pmt','http://tipsy.googlecode.com/svn/trunk/vocab/pmt#',335),
	('pna','http://data.press.net/ontology/asset/',892),
	('pnc','http://data.press.net/ontology/classification/',1400),
	('pne','http://data.press.net/ontology/event/',914),
	('pni','http://data.press.net/ontology/identifier/',1402),
	('pns','http://data.press.net/ontology/stuff/',754),
	('pnt','http://data.press.net/ontology/tag/',1395),
	('po','http://purl.org/ontology/po/',135),
	('pobo','http://purl.obolibrary.org/obo/',503),
	('poder','http://poderopedia.com/vocab/',732),
	('pois','http://purl.oclc.org/POIS/vcblr#',1022),
	('pol','http://escience.rpi.edu/ontology/semanteco/2/0/pollution.owl#',775),
	('politico','http://www.rdfabout.com/rdf/schema/politico/',163),
	('pom','http://maven.apache.org/POM/4.0.0#',602),
	('pos','http://www.w3.org/2003/01/geo/wgs84_pos#',637),
	('posh','http://poshrdf.org/ns/posh/',473),
	('postcode','http://data.ordnancesurvey.co.uk/id/postcodeunit/',441),
	('poste','http://data.lirmm.fr/ontologies/poste#',993),
	('powder','http://www.w3.org/2007/05/powder#',204),
	('ppo','http://vocab.deri.ie/ppo#',674),
	('pproc','http://contsem.unizar.es/def/sector-publico/pproc#',1242),
	('pr','http://purl.org/ontology/prv/core#',149),
	('prefix','http://prefix.cc/',660),
	('premis','http://multimedialab.elis.ugent.be/users/samcoppe/ontologies/Premis/premis.owl#',946),
	('prf','http://www.openmobilealliance.org/tech/profiles/UAPROF/ccppschema-20021212#',930),
	('prism','http://prismstandard.org/namespaces/basic/2.0/',305),
	('prism21','http://prismstandard.org/namespaces/basic/2.1/',801),
	('prissma','http://ns.inria.fr/prissma/v1#',360),
	('prj','http://purl.org/stuff/project/',258),
	('pro','http://purl.org/hpi/patchr#',630),
	('product','http://purl.org/commerce/product#',304),
	('profiling','http://ontologi.es/profiling#',345),
	('prog','http://purl.org/prog/',624),
	('prolog','http://eulersharp.sourceforge.net/2003/03swap/prolog#',1017),
	('pronom','http://reference.data.gov.uk/technical-registry/',848),
	('prot','http://www.proteinontology.info/po.owl#',454),
	('protege','http://protege.stanford.edu/system#',185),
	('protegedc','http://protege.stanford.edu/plugins/owl/dc/protege-dc.owl#',836),
	('protons','http://proton.semanticweb.org/2005/04/protons#',506),
	('prov','http://www.w3.org/ns/prov#',70),
	('provenir','http://knoesis.wright.edu/provenir/provenir.owl#',538),
	('provone','http://purl.org/provone#',1252),
	('prv','http://purl.org/net/provenance/ns#',137),
	('prviv','http://purl.org/net/provenance/integrity#',908),
	('prvr','http://purl.org/ontology/prv/rules#',577),
	('prvt','http://purl.org/net/provenance/types#',1049),
	('prvtypes','http://purl.org/net/provenance/types#',452),
	('ps','https://w3id.org/payswarm#',408),
	('psh','http://psh.techlib.cz/skos/',828),
	('pso','http://purl.org/spar/pso/',1117),
	('psych','http://purl.org/vocab/psychometric-profile/',354),
	('psys','http://www.ontotext.com/proton/protonsys#',1377),
	('pto','http://www.productontology.org/id/',43),
	('ptop','http://www.ontotext.com/proton/protontop#',1113),
	('ptr','http://www.w3.org/2009/pointers#',297),
	('pubmed','http://bio2rdf.org/pubmed_vocabulary:',1058),
	('puc','http://purl.org/NET/puc#',338),
	('puelia','http://kwijibo.talis.com/vocabs/puelia#',951),
	('purl','http://purl.org/dc/terms/',1179),
	('push','http://www.w3.org/2007/uwa/context/push.owl#',358),
	('pvcs','http://purl.org/twc/vocab/pvcs#',1326),
	('pwo','http://purl.org/spar/pwo/',1172),
	('qa','http://www.mit.jyu.fi/ai/TRUST_Ontologies/QA.owl#',860),
	('qb','http://purl.org/linked-data/cube#',31),
	('qb4o','http://purl.org/olap#',900),
	('qdoslf','http://foaf.qdos.com/lastfm/schema/',332),
	('ql','http://www.w3.org/2004/ql#',890),
	('qrl','http://www.aifb.kit.edu/project/ld-retriever/qrl#',1000),
	('qu','http://purl.oclc.org/NET/ssnx/qu/qu#',1373),
	('quak','http://dev.w3.org/cvsweb/2000/quacken/vocab#',543),
	('quantities','http://eulersharp.sourceforge.net/2003/03swap/quantitiesExtension#',599),
	('qud','http://qudt.org/1.1/schema/qudt#',997),
	('qudt','http://qudt.org/1.1/schema/qudt#',642),
	('quty','http://www.telegraphis.net/ontology/measurement/quantity#',1150),
	('qvoc','http://mlode.nlp2rdf.org/quranvocab#',972),
	('r2r','http://www4.wiwiss.fu-berlin.de/bizer/r2r/',499),
	('r2rml','http://www.w3.org/ns/r2rml#',873),
	('r4ta','http://ns.inria.fr/ratio4ta/v1#',842),
	('rad','http://www.w3.org/ns/rad#',881),
	('radion','http://www.w3.org/ns/radion#',1030),
	('rail','http://ontologi.es/rail/vocab#',493),
	('ramon','http://rdfdata.eionet.europa.eu/ramon/ontology/',1410),
	('rating','http://www.tvblob.com/ratings/#',669),
	('raul','http://vocab.deri.ie/raul#',1165),
	('rda','http://www.rdaregistry.info/',634),
	('rdaa','http://rdaregistry.info/Elements/a/',1223),
	('rdac','http://rdaregistry.info/Elements/c/',1211),
	('rdacarrier','http://rdvocab.info/termList/RDACarrierType/',989),
	('rdacontent','http://rdvocab.info/termList/RDAContentType/',1018),
	('rdae','http://rdaregistry.info/Elements/e/',1235),
	('rdafrbr','http://rdvocab.info/uri/schema/FRBRentitiesRDA/',1056),
	('rdag1','http://rdvocab.info/Elements/',1067),
	('rdag2','http://rdvocab.info/ElementsGr2/',1379),
	('rdag3','http://rdvocab.info/ElementsGr3/',1114),
	('rdagr1','http://rdvocab.info/Elements/',708),
	('rdai','http://rdaregistry.info/Elements/i/',1265),
	('rdam','http://rdaregistry.info/Elements/m/',1229),
	('rdamedia','http://rdvocab.info/termList/RDAMediaType/',935),
	('rdarel','http://rdvocab.info/RDARelationshipsWEMI/',1050),
	('rdarel2','http://metadataregistry.org/uri/schema/RDARelationshipsGR2/',1392),
	('rdarole','http://rdvocab.info/roles/',712),
	('rdau','http://rdaregistry.info/Elements/u/',1228),
	('rdaw','http://rdaregistry.info/Elements/w/',1209),
	('rdb','http://www.dbs.cs.uni-duesseldorf.de/RDF/relational#',792),
	('rdf','http://www.w3.org/1999/02/22-rdf-syntax-ns#',2),
	('rdf123','http://rdf123.umbc.edu/ns/',945),
	('rdfa','http://www.w3.org/ns/rdfa#',324),
	('rdfdata','http://rdf.data-vocabulary.org/rdf.xml#',1012),
	('rdfdf','http://www.openlinksw.com/virtrdf-data-formats#',723),
	('rdfg','http://www.w3.org/2004/03/trix/rdfg-1/',99),
	('rdfs','http://www.w3.org/2000/01/rdf-schema#',7),
	('rdl','http://data.posccaesar.org/rdl/',1249),
	('rdo','http://purl.org/rdo/ns#',653),
	('rdrel','http://rdvocab.info/RDARelationshipsWEMI/',667),
	('re','http://www.w3.org/2000/10/swap/reason#',849),
	('rec','http://purl.org/ontology/rec/core#',212),
	('rec54','http://www.w3.org/2001/02pd/rec54.rdf#',746),
	('recipe','http://linkedrecipes.org/schema/',790),
	('reco','http://purl.org/reco#',86),
	('reegle','http://reegle.info/schema#',1376),
	('ref','http://purl.org/vocab/relationship/',415),
	('refe','http://orion.tw.rpi.edu/~xgmatwc/refe/',980),
	('rei','http://www.w3.org/2004/06/rei#',222),
	('rel','http://purl.org/vocab/relationship/',54),
	('religion','http://rdf.muninn-project.org/ontologies/religion#',1466),
	('remus','http://www.semanticweb.org/ontologies/2010/6/Ontology1279614123500.owl#',432),
	('rep','http://www.openrdf.org/config/repository#',198),
	('req','http://purl.org/req/',558),
	('res','http://www.w3.org/2005/sparql-results#',519),
	('resex','http://resex.rkbexplorer.com/ontologies/resex#',203),
	('resist','http://www.rkbexplorer.com/ontologies/resist#',249),
	('resource','http://purl.org/vocab/resourcelist/schema#',311),
	('rev','http://purl.org/stuff/rev#',89),
	('reve','http://data.eurecom.fr/ontology/reve#',964),
	('rich','http://rdf.data-vocabulary.org/',814),
	('rif','http://www.w3.org/2007/rif#',105),
	('rlno','http://rdflivenews.aksw.org/ontology/',957),
	('rlnr','http://rdflivenews.aksw.org/resource/',986),
	('rlog','http://persistence.uni-leipzig.org/nlp2rdf/ontologies/rlog#',738),
	('rmo','http://eatld.et.tu-dresden.de/rmo#',1462),
	('rnews','http://iptc.org/std/rNews/2011-10-07#',447),
	('ro','http://purl.org/wf4ever/ro#',405),
	('roadmap','http://mappings.roadmap.org/',1354),
	('roevo','http://purl.org/wf4ever/roevo#',1045),
	('role','http://purl.org/vocab/participation/schema#',1092),
	('room','http://vocab.deri.ie/rooms#',298),
	('rooms','http://vocab.deri.ie/rooms#',391),
	('roterms','http://purl.org/wf4ever/roterms#',1038),
	('rov','http://www.w3.org/ns/regorg#',632),
	('rpubl','http://rinfo.lagrummet.se/ns/2008/11/rinfo/publ#',878),
	('rr','http://www.w3.org/ns/r2rml#',232),
	('rsa','http://www.w3.org/ns/auth/rsa#',130),
	('rso','http://www.researchspace.org/ontology/',1195),
	('rss','http://purl.org/rss/1.0/',12),
	('rssynd','http://web.resource.org/rss/1.0/modules/syndication/',865),
	('ru','http://purl.org/imbi/ru-meta.owl#',1394),
	('rulz','http://purl.org/NET/rulz#',443),
	('ruto','http://rdfunit.aksw.org/ns/core#',1312),
	('rv','http://wifo-ravensburg.de/semanticweb.rdf#',672),
	('rvl','http://purl.org/rvl/',1335),
	('s2s','http://escience.rpi.edu/ontology/sesf/s2s/4/0/',805),
	('s3db','http://www.s3db.org/core#',895),
	('s4ac','http://ns.inria.fr/s4ac/v2#',528),
	('sad','http://vocab.deri.ie/sad#',1300),
	('saif','http://wwwiti.cs.uni-magdeburg.de/~srahman/',1036),
	('sail','http://www.openrdf.org/config/sail#',244),
	('sam','http://def.seegrid.csiro.au/isotc211/iso19156/2011/sampling#',1361),
	('sao','http://salt.semanticauthoring.org/ontologies/sao#',1381),
	('sawsdl','http://www.w3.org/ns/sawsdl#',417),
	('saxon','http://saxon.sf.net/',693),
	('sbench','http://swat.cse.lehigh.edu/onto/univ-bench.owl#',1399),
	('sc','http://purl.org/science/owl/sciencecommons/',16),
	('schema','http://schema.org/',131),
	('sci','http://data.scientology.org/ns/',888),
	('scip','http://lod.taxonconcept.org/ontology/sci_people.owl#',1371),
	('scms','http://ns.aksw.org/scms/annotations/',1110),
	('sco','http://purl.org/ontology/sco#',562),
	('scoro','http://purl.org/spar/scoro/',1386),
	('scot','http://rdfs.org/scot/ns#',207),
	('scovo','http://purl.org/NET/scovo#',165),
	('scowt','http://purl.org/weso/ontologies/scowt#',611),
	('scsv','http://purl.org/NET/schema-org-csv#',658),
	('scufl2','http://ns.taverna.org.uk/2010/scufl2#',856),
	('scv','http://purl.org/NET/scovo#',334),
	('sd','http://www.w3.org/ns/sparql-service-description#',55),
	('sdgp','http://stats.data-gov.ie/property/',822),
	('sdl','http://purl.org/vocab/riro/sdl#',277),
	('sdmx','http://purl.org/linked-data/sdmx#',343),
	('sdmxa','http://purl.org/linked-data/sdmx/2009/attribute#',949),
	('sdmxd','http://purl.org/linked-data/sdmx/2009/dimension#',1111),
	('sdmxdim','http://purl.org/linked-data/sdmx/2009/dimension#',933),
	('sdo','http://salt.semanticauthoring.org/ontologies/sdo#',1051),
	('search','http://sindice.com/vocab/search#',457),
	('sec','https://w3id.org/security#',451),
	('security','http://securitytoolbox.appspot.com/securityMain#',1353),
	('sede','http://eventography.org/sede/0.1/',178),
	('sem','http://semanticweb.cs.vu.nl/2009/11/sem/',845),
	('semio','http://www.lingvoj.org/semio#',1174),
	('semtweet','http://semantictweet.com/',628),
	('seq','http://www.ontologydesignpatterns.org/cp/owl/sequence.owl#',1187),
	('service','http://purl.org/ontology/service#',785),
	('ses','http://lod.taxonconcept.org/ses/',1289),
	('sesame','http://www.openrdf.org/schema/sesame#',315),
	('session','http://redfoot.net/2005/session#',481),
	('set','http://www.w3.org/2000/10/swap/set#',812),
	('sf','http://www.opengis.net/ont/sf#',1042),
	('sgv','http://www.w3.org/TR/SVG/',789),
	('shex','http://www.w3.org/2013/ShEx/ns#',1329),
	('shv','http://ns.aksw.org/spatialHierarchy/',668),
	('shw','http://paul.staroch.name/thesis/SmartHomeWeather.owl#',1409),
	('sider','http://www4.wiwiss.fu-berlin.de/sider/resource/sider/',126),
	('sig','http://purl.org/signature#',588),
	('sim','http://purl.org/ontology/similarity/',317),
	('sindice','http://vocab.sindice.net/',486),
	('sio','http://semanticscience.org/resource/',480),
	('sioc','http://rdfs.org/sioc/ns#',15),
	('sioca','http://rdfs.org/sioc/actions#',448),
	('siocserv','http://rdfs.org/sioc/services#',1253),
	('sioct','http://rdfs.org/sioc/types#',133),
	('sioctypes','http://rdfs.org/sioc/types#',662),
	('sism','http://purl.oclc.org/NET/sism/0.1/',97),
	('sit','http://www.ontologydesignpatterns.org/cp/owl/situation.owl#',240),
	('site','http://ns.ontowiki.net/SysOnt/Site/',459),
	('situ','http://www.ontologydesignpatterns.org/cp/owl/situation.owl#',1106),
	('skip','http://skipforward.net/skipforward/resource/',646),
	('skiresort','http://www.openlinksw.com/ski_resorts/schema#',760),
	('skos','http://www.w3.org/2004/02/skos/core#',11),
	('skos08','http://www.w3.org/2008/05/skos#',1225),
	('skosxl','http://www.w3.org/2008/05/skos-xl#',179),
	('sl','http://www.semanlink.net/2001/00/semanlink-schema#',427),
	('sm','http://topbraid.org/sparqlmotion#',407),
	('smf','http://topbraid.org/sparqlmotionfunctions#',312),
	('smg','http://ns.cerise-project.nl/energy/def/cim-smartgrid#',1374),
	('smiley','http://www.smileyontology.com/ns#',310),
	('sml','http://topbraid.org/sparqlmotionlib#',322),
	('snarm','http://rdf.myexperiment.org/ontologies/snarm/',1200),
	('so','http://purl.org/ontology/symbolic-music/',210),
	('soap','http://www.w3.org/2003/05/soap-envelope/',681),
	('soc','http://purl.org/net/hdlipcores/ontology/soc#',1257),
	('soft','http://www.w3.org/2007/uwa/context/software.owl#',366),
	('sp','http://spinrdf.org/sp#',228),
	('space','http://purl.org/net/schemas/space/',259),
	('spacerel','http://data.ordnancesurvey.co.uk/ontology/spatialrelations/',124),
	('span','http://www.ifomis.org/bfo/1.1/span#',606),
	('sparql','http://ontologi.es/sparql#',394),
	('spatial','http://geovocab.org/spatial#',613),
	('spc','http://purl.org/ontomedia/core/space#',225),
	('spcm','http://spi-fm.uca.es/spdef/models/deployment/spcm/1.0#',1404),
	('spdx','http://spdx.org/rdf/terms#',1297),
	('spfood','http://kmi.open.ac.uk/projects/smartproducts/ontologies/food.owl#',1375),
	('spif','http://spinrdf.org/spif#',886),
	('spin','http://spinrdf.org/spin#',205),
	('spl','http://spinrdf.org/spl#',209),
	('sport','http://www.bbc.co.uk/ontologies/sport/',440),
	('spt','http://spitfire-project.eu/ontology/ns/',1199),
	('sql','http://ns.inria.fr/ast/sql#',782),
	('sr','http://www.openrdf.org/config/repository/sail#',95),
	('sro','http://salt.semanticauthoring.org/ontologies/sro#',1336),
	('sru','http://www.loc.gov/zing/srw/',1302),
	('ssn','http://purl.oclc.org/NET/ssnx/ssn#',552),
	('sso','http://nlp2rdf.lod2.eu/schema/sso/',939),
	('ssso','http://purl.org/ontology/ssso#',1004),
	('st','http://semweb.mmlab.be/ns/stoptimes#',1406),
	('stac','http://securitytoolbox.appspot.com/stac#',944),
	('stanford','http://purl.org/olia/stanford.owl#',1261),
	('states','http://www.w3.org/2005/07/aaa#',378),
	('static','http://vocab-ld.org/vocab/static-ld#',1279),
	('stats','http://purl.org/rdfstats/stats#',970),
	('status','http://ontologi.es/status#',429),
	('steel','http://ontorule-project.eu/resources/steel-30#',772),
	('stories','http://purl.org/ontology/stories/',1384),
	('str','http://nlp2rdf.lod2.eu/schema/string/',774),
	('strdf','http://strdf.di.uoa.gr/ontology#',1013),
	('stream','http://dbpedia.org/ontology/Stream/',1122),
	('string','http://www.w3.org/2000/10/swap/string#',361),
	('sv','http://schemas.talis.com/2005/service/schema#',291),
	('swanag','http://purl.org/swan/1.2/agents/',373),
	('swanci','http://purl.org/swan/1.2/citations/',420),
	('swanco','http://purl.org/swan/1.2/swan-commons/',389),
	('swande','http://purl.org/swan/1.2/discourse-elements/',110),
	('swandr','http://purl.org/swan/1.2/discourse-relationships/',313),
	('swanpav','http://purl.org/swan/1.2/pav/',362),
	('swanq','http://purl.org/swan/1.2/qualifiers/',103),
	('swanqs','http://purl.org/swan/1.2/qualifiers/',300),
	('swc','http://data.semanticweb.org/ns/swc/ontology#',68),
	('swh','http://plugin.org.uk/swh-plugins/',368),
	('swid','http://semanticweb.org/id/',436),
	('swivt','http://semantic-mediawiki.org/swivt/1.0#',413),
	('swp','http://www.w3.org/2004/03/trix/swp-2/',328),
	('swpatho','http://swpatho.ag-nbi.de/context/meta.owl#',960),
	('swperson','http://data.semanticweb.org/person/',1037),
	('swpm','http://spi-fm.uca.es/spdef/models/deployment/swpm/1.0#',1414),
	('swpo','http://sw-portal.deri.org/ontologies/swportal#',1190),
	('swrc','http://swrc.ontoware.org/ontology#',33),
	('swrcfe','http://www.morelab.deusto.es/ontologies/swrcfe#',1168),
	('swrl','http://www.w3.org/2003/11/swrl#',141),
	('swrlb','http://www.w3.org/2003/11/swrlb#',164),
	('sysont','http://ns.ontowiki.net/SysOnt/',437),
	('tac','http://ns.bergnet.org/tac/0.1/triple-access-control#',1368),
	('tag','http://www.holygoat.co.uk/owl/redwood/0.1/tags/',64),
	('tags','http://www.holygoat.co.uk/owl/redwood/0.1/tags/',308),
	('tao','http://vocab.deri.ie/tao#',1186),
	('tarot','http://data.totl.net/tarot/card/',471),
	('tavprov','http://ns.taverna.org.uk/2012/tavernaprov/',1277),
	('taxo','http://purl.org/rss/1.0/modules/taxonomy/',158),
	('taxon','http://purl.org/biodiversity/taxon/',1364),
	('tblcard','http://www.w3.org/People/Berners-Lee/card#',981),
	('tcga','http://purl.org/tcga/core#',729),
	('tdb','http://jena.hpl.hp.com/2008/tdb#',327),
	('tddo','http://databugger.aksw.org/ns/core#',1184),
	('te','http://www.w3.org/2006/time-entry#',1170),
	('teach','http://linkedscience.org/teach/ns#',716),
	('tei','http://www.tei-c.org/ns/1.0/',612),
	('telix','http://purl.org/telix#',718),
	('telmap','http://purl.org/telmap/',883),
	('test','http://test2.example.com/',151),
	('test2','http://this.invalid/test2#',53),
	('tgn','http://vocab.getty.edu/tgn/',1204),
	('theatre','http://purl.org/theatre#',616),
	('thors','http://resource.geosciml.org/ontology/timescale/thors#',1363),
	('ti','http://www.ontologydesignpatterns.org/cp/owl/timeinterval.owl#',201),
	('time','http://www.w3.org/2006/time#',146),
	('timeline','http://purl.org/NET/c4dm/timeline.owl#',402),
	('tio','http://purl.org/tio/ns#',364),
	('tis','http://www.ontologydesignpatterns.org/cp/owl/timeindexedsituation.owl#',1202),
	('tisc','http://observedchange.com/tisc/ns#',915),
	('tl','http://purl.org/NET/c4dm/timeline.owl#',180),
	('tm','http://def.seegrid.csiro.au/isotc211/iso19108/2002/temporal#',1350),
	('tmo','http://www.semanticdesktop.org/ontologies/2008/05/20/tmo#',150),
	('tmpl','http://purl.org/restdesc/http-template#',735),
	('toby','http://tobyinkster.co.uk/#',572),
	('topo','http://data.ign.fr/def/topo#',1315),
	('tr','http://www.thomsonreuters.com/',1007),
	('trackback','http://madskills.com/public/xml/rss/module/trackback/',336),
	('trait','http://contextus.net/ontology/ontomedia/ext/common/trait#',1205),
	('transit','http://vocab.org/transit/terms/',721),
	('transmed','http://www.w3.org/2001/sw/hcls/ns/transmed/',620),
	('travel','http://www.co-ode.org/roberts/travel.owl#',1255),
	('trig','http://www.w3.org/2004/03/trix/rdfg-1/',1346),
	('tripfs','http://purl.org/tripfs/2010/02#',349),
	('tripfs2','http://purl.org/tripfs/2010/06#',571),
	('tsioc','http://rdfs.org/sioc/types#',1134),
	('ttl','http://www.w3.org/2008/turtle#',404),
	('turismo','http://idi.fundacionctic.org/cruzar/turismo#',1156),
	('tvc','http://www.essepuntato.it/2012/04/tvc/',1066),
	('tw','http://tw.rpi.edu/schema/',1148),
	('twaapi','http://purl.org/twc/vocab/aapi-schema#',1055),
	('txn','http://lod.taxonconcept.org/ontology/txn.owl#',414),
	('tzont','http://www.w3.org/2006/timezone#',108),
	('ub','http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#',906),
	('uco','http://purl.org/uco/ns#',788),
	('ufmedia','http://purl.org/microformat/hmedia/',485),
	('ui','http://www.w3.org/ns/ui#',508),
	('uis','http://uis.270a.info/dataset/',1357),
	('ulan','http://vocab.getty.edu/ulan/',1224),
	('umbel','http://umbel.org/umbel#',170),
	('umbelrc','http://umbel.org/umbel/rc/',587),
	('un','http://www.w3.org/2007/ont/unit#',903),
	('uni','http://purl.org/weso/uni/uni.html#',627),
	('uniprot','http://purl.uniprot.org/core/',138),
	('unit','http://qudt.org/vocab/unit#',238),
	('units','http://eulersharp.sourceforge.net/2003/03swap/unitsExtension#',590),
	('unspsc','http://ontoview.org/schema/unspsc/1#',1286),
	('up','http://users.ugent.be/~tdenies/up/',1003),
	('uri','http://purl.org/NET/uri#',419),
	('uri4uri','http://uri4uri.net/vocab#',1259),
	('urn','http://fliqz.com/',395),
	('user','http://schemas.talis.com/2005/user/schema#',193),
	('usgov','http://www.rdfabout.com/rdf/schema/usgovt/',172),
	('uta','http://uptheasset.org/ontology#',891),
	('va','http://code-research.eu/ontology/visual-analytics#',1321),
	('vaem','http://www.linkedmodel.org/schema/vaem#',686),
	('vann','http://purl.org/vocab/vann/',42),
	('vapour','http://vapour.sourceforge.net/vocab.rdf#',1011),
	('vcard','http://www.w3.org/2006/vcard/ns#',36),
	('vcard2006','http://www.w3.org/2006/vcard/ns#',804),
	('vcardx','http://buzzword.org.uk/rdf/vcardx#',783),
	('vdpp','http://data.lirmm.fr/ontologies/vdpp#',887),
	('vext','http://ldf.fi/void-ext#',1285),
	('vgo','http://purl.org/net/VideoGameOntology#',1264),
	('viaf','http://viaf.org/ontology/1.1/#',685),
	('video','http://purl.org/media/video#',248),
	('videogame','http://purl.org/net/vgo#',1258),
	('vin','http://www.w3.org/TR/2003/PR-owl-guide-20031209/wine#',1318),
	('visit','http://purl.org/net/vocab/2004/07/visit#',631),
	('visko','http://trust.utep.edu/visko/ontology/visko-operator-v3.owl#',907),
	('viskoo','http://trust.utep.edu/visko/ontology/visko-operator-v3.owl#',1021),
	('viskov','http://trust.utep.edu/visko/ontology/visko-view-v3.owl#',961),
	('viso','http://purl.org/viso/',1126),
	('vitro','http://vitro.mannlib.cornell.edu/ns/vitro/public#',570),
	('vivo','http://vivoweb.org/ontology/core#',724),
	('vmm','http://spi-fm.uca.es/spdef/models/genericTools/vmm/1.0#',1351),
	('voaf','http://purl.org/vocommons/voaf#',357),
	('voag','http://voag.linkedmodel.org/schema/voag#',626),
	('vocab','http://rdf.ontology2.com/vocab#',936),
	('void','http://rdfs.org/ns/void#',30),
	('voidext','http://rdfs.org/ns/void-ext#',1352),
	('voidp','http://www.enakting.org/provenance/voidp/',917),
	('voidwh','http://www.ics.forth.gr/isl/VoIDWarehouse/VoID_Extension_Schema.owl#',1332),
	('vote','http://www.rdfabout.com/rdf/schema/vote/',194),
	('vra','http://simile.mit.edu/2003/10/ontologies/vraCore3#',1330),
	('vrank','http://purl.org/voc/vrank#',1086),
	('vs','http://www.w3.org/2003/06/sw-vocab-status/ns#',125),
	('vso','http://purl.org/vso/ns#',569),
	('vsr','http://purl.org/twc/vocab/vsr#',533),
	('vsto','http://escience.rpi.edu/ontology/vsto/2/0/vsto.owl#',852),
	('vsw','http://verticalsearchworks.com/ontology/',929),
	('vsws','http://verticalsearchworks.com/ontology/synset#',921),
	('vvo','http://purl.org/vvo/ns#',991),
	('w3con','http://www.w3.org/2000/10/swap/pim/contact#',841),
	('w3p','http://prov4j.org/w3p/',468),
	('w3po','http://purl.org/provenance/w3p/w3po#',968),
	('wai','http://purl.org/wai#',596),
	('wairole','http://www.w3.org/2005/01/wai-rdf/GUIRoleTaxonomy#',406),
	('wao','http://webtlab.it.uc3m.es/2010/10/WebAppsOntology#',583),
	('wapp','http://ns.rww.io/wapp#',976),
	('water','http://escience.rpi.edu/ontology/semanteco/2/0/water.owl#',925),
	('wbc','http://worldbank.270a.info/classification/',992),
	('wbp','http://worldbank.270a.info/property/',1024),
	('wd','http://www.wikidata.org/entity/',922),
	('wdr','http://www.w3.org/2007/05/powder#',294),
	('wdrs','http://www.w3.org/2007/05/powder-s#',157),
	('web','http://www.w3.org/2007/uwa/context/web.owl#',371),
	('webbox','http://webbox.ecs.soton.ac.uk/ns#',955),
	('webtlab','http://webtlab.it.uc3m.es/',521),
	('wf','http://www.w3.org/2005/01/wf/flow#',622),
	('wf4ever','http://purl.org/wf4ever/wf4ever#',1059),
	('wfdesc','http://purl.org/wf4ever/wfdesc#',811),
	('wfm','http://purl.org/net/wf-motifs#',918),
	('wfn','http://webofcode.org/wfn/',1305),
	('wfprov','http://purl.org/wf4ever/wfprov#',813),
	('wfs','http://schemas.opengis.net/wfs/',928),
	('wgs','http://www.w3.org/2003/01/geo/wgs84_pos#',398),
	('wgs84','http://www.w3.org/2003/01/geo/wgs84_pos#',270),
	('wgspos','http://www.w3.org/2003/01/geo/wgs84_pos#',478),
	('whisky','http://vocab.org/whisky/terms/',1342),
	('who','http://www.who.int/vocab/ontology#',1083),
	('whois','http://www.kanzaki.com/ns/whois#',197),
	('wi','http://purl.org/ontology/wi/core#',1046),
	('wiki','http://en.wikipedia.org/wiki/',1054),
	('wikidata','http://www.wikidata.org/entity/',1019),
	('wikim','http://spi-fm.uca.es/spdef/models/genericTools/wikim/1.0#',1365),
	('wikimedia','http://upload.wikimedia.org/wikipedia/commons/f/f6/',1344),
	('wikipedia','http://www.systemone.at/2006/03/wikipedia#',866),
	('wikterms','http://wiktionary.dbpedia.org/terms/',855),
	('wisski','http://wiss-ki.eu/',393),
	('wkd','http://schema.wolterskluwer.de/',978),
	('wl','http://www.wsmo.org/ns/wsmo-lite#',923),
	('wlo','http://purl.org/ontology/wo/',1079),
	('wlp','http://weblab-project.org/core/model/property/processing/',458),
	('wm','http://ns.inria.fr/webmarks#',784),
	('wn','http://xmlns.com/wordnet/1.6/',161),
	('wn20','http://www.w3.org/2006/03/wn/wn20/',869),
	('wn20schema','http://www.w3.org/2006/03/wn/wn20/schema/',128),
	('wn30','http://purl.org/vocabularies/princeton/wn30/',1325),
	('wn31','http://wordnet-rdf.princeton.edu/wn31/',1431),
	('wno','http://wordnet-rdf.princeton.edu/ontology#',1448),
	('wnschema','http://www.cogsci.princeton.edu/~wn/schema/',281),
	('wo','http://purl.org/ontology/wo/',145),
	('won','http://purl.org/webofneeds/model#',1001),
	('wordmap','http://purl.org/net/ns/wordmap#',239),
	('wordnet','http://purl.org/vocabularies/princeton/wordnet/schema#',530),
	('worldbank','http://worldbank.270a.info/dataset/',1043),
	('wot','http://xmlns.com/wot/0.1/',45),
	('wp','http://vocabularies.wikipathways.org/',954),
	('wro','http://purl.org/net/wf4ever/ro#',1378),
	('wsc','http://www.openk.org/wscaim.owl#',1016),
	('wscaim','http://www.openk.org/wscaim.owl#',850),
	('wsl','http://www.wsmo.org/ns/wsmo-lite#',1088),
	('wv','http://vocab.org/waiver/terms/',303),
	('xbrli','http://www.xbrl.org/2003/instance#',461),
	('xch','http://oanda2rdf.appspot.com/xch/',791),
	('xds','http://www.w3.org/2001/XMLSchema#',629),
	('xen','http://buzzword.org.uk/rdf/xen#',256),
	('xesam','http://freedesktop.org/standards/xesam/1.0/core#',410),
	('xf','http://www.w3.org/2002/xforms/',102),
	('xfn','http://vocab.sindice.com/xfn#',93),
	('xfnv','http://vocab.sindice.com/xfn#',516),
	('xforms','http://www.w3.org/2002/xforms/',381),
	('xhe','http://buzzword.org.uk/rdf/xhtml-elements#',285),
	('xhtml','http://www.w3.org/1999/xhtml#',37),
	('xhtmlvocab','http://www.w3.org/1999/xhtml/vocab/',401),
	('xhv','http://www.w3.org/1999/xhtml/vocab#',90),
	('xkos','http://purl.org/linked-data/xkos#',697),
	('xl','http://langegger.at/xlwrap/vocab#',382),
	('xlime','http://xlime-project.org/vocab/',1439),
	('xlink','http://www.w3.org/1999/xlink/',843),
	('xml','http://www.w3.org/XML/1998/namespace/',1194),
	('xmls','http://www.w3.org/2001/XMLSchema#',769),
	('xmp','http://ns.adobe.com/xap/1.0/',1044),
	('xro','http://purl.org/xro/ns#',292),
	('xs','http://www.w3.org/2001/XMLSchema#',94),
	('xsd','http://www.w3.org/2001/XMLSchema#',19),
	('xsi','http://www.w3.org/2001/XMLSchema-instance#',1140),
	('xsl','http://www.w3.org/1999/XSL/Transform#',551),
	('xslopm','http://purl.org/net/opmv/types/xslt#',1333),
	('xt','http://purl.org/twc/vocab/cross-topix#',879),
	('xtypes','http://purl.org/xtypes/',175),
	('ya','http://blogs.yandex.ru/schema/foaf/',184),
	('yago','http://yago-knowledge.org/resource/',1),
	('yoda','http://purl.org/NET/yoda#',444),
	('zbwext','http://zbw.eu/namespaces/zbw-extensions/',504),
	('zem','http://s.zemanta.com/ns#',591),
	('zoology','http://purl.org/NET/biol/zoology#',174),
	('zoomaterms','http://rdf.ebi.ac.uk/vocabulary/zooma/',1026),
	('zr','http://explain.z3950.org/dtd/2.0/',1331);
ALTER TABLE `reg_prefix` ENABLE KEYS;
UNLOCK TABLES;


LOCK TABLES `reg_rdf_namespace` WRITE;
ALTER TABLE `reg_rdf_namespace` DISABLE KEYS;
ALTER TABLE `reg_rdf_namespace` ENABLE KEYS;
UNLOCK TABLES;




SET FOREIGN_KEY_CHECKS = @PREVIOUS_FOREIGN_KEY_CHECKS;


