generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      VocabularyHasUser
    theme:            default
    fields:
      id:                { name: ID, type: plain, credentials: [administrator] }
      created_at:        { name: Date Created, type: plain, credentials: [administrator] }
      updated_at:        { name: Last Updated, type: plain, credentials: [administrator] }
      is_admin_for:      { name: Administrator }
      is_registrar_for:  { name: Registrar }
      is_maintainer_for: { name: Maintainer }

    list:
      #peer_method:       doSelectJoinAll
      #peer_count_method: doCountForUser
      title:              Maintainers for %%vocabulary%%
      display:            [_user, _vocabulary, isRegistrarFor, isAdminFor, isMaintainerFor]
      object_actions:
        _show:
        _edit:            { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _delete:          { credentials: [[administrator, vocabularyadmin, agentadmin]] }
      actions:
        _create:          {query_string: {vocabulary_id: vocabulary_id}, name: Add Maintainer, credentials: [[administrator, vocabularyadmin, agentadmin]] }
      displayfilter:      false
      filters:            [vocabulary_id, user_id]
      urlfilters:
        vocabulary_id:    vocabulary_id
        user_id:          user_id

    edit:
      title:
        mode:
          edit:       Editing %%vocabulary%% permissions for %%user%%
          create:     Adding maintainer to %%vocabulary%%
      helptype:       icon
      fields:
        user_id:       { params: peer_method=getNewUsersForVocabulary include_blank=false, mode: create }
        user:          { type: plain, mode: edit }
      display:         [user, user_id, isAdminFor, isMaintainerFor]
      actions:
        _save:         { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _delete:       { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _create:       { name: Add Maintainer, credentials: [[administrator, vocabularyadmin, agentadmin]], mode: edit  }
        _save_and_add: { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _cancel:       { credentials: [[administrator, vocabularyadmin, agentadmin]] }

    show:
      title:           %%vocabulary%% permissions for %%user%%
      fields:
        user:          { type: plain }
      display:         [user, isRegistrarFor, isAdminFor, isMaintainerFor]
      actions:
        _delete:       { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _edit:         { credentials: [[administrator, vocabularyadmin, agentadmin]] }
        _create:       { name: Add Maintainer, credentials: [[administrator, vocabularyadmin, agentadmin]] }
