generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      VocabularyHasUser
    theme:            default

    list:
      #peer_method:       doSelectForUser
      #peer_count_method: doCountForUser
      title:             Vocabulary and User Relationships
      display:           [_user, _vocabulary, isRegistrarFor, isAdminFor, isMaintainerFor]
      object_actions:
        _edit:           { credentials: [administrator] }
        _delete:         { credentials: [administrator] }
      actions:
        _create:         { credentials: [administrator] }
      displayfilter:    false
      filters:          [vocabulary_id, user_id]
      urlfilters:
        vocabulary_id:   vocabulary_id
        user_id:         user_id

    edit:
      helptype:       icon
      fields:
        vocabulary_id:  { params: peer_method=getVocabulariesForCurrentUser include_blank=true }
        user_id:        { params: peer_method=getUsersForAgentUsers include_blank=true }
        user:          { type: plain }
        vocabulary:    { type: plain }
      display:         [user_id, vocabulary_id, isAdminFor, isRegistrarFor, isMaintainerFor]
      actions:
        _list:      -
        _save:         { credentials: [[administrator, hasAgents, vocabularymaintainer]] }
        _delete:       { credentials: [administrator] }
        _create:       { credentials: [[administrator, hasAgents]] }
        _save_and_add: { credentials: [administrator] }
        _cancel:       { credentials: [[administrator, hasAgents, vocabularymaintainer]] }
