<?php
// auto-generated by sfPropelAdmin
// date: 2017/03/31 19:11:08
/** @var sfContext $sf_context */
/** @var sfParameterHolder $sf_flash */
/** @var sfParameterHolder $sf_params */
/** @var myWebRequest $sf_request */
/** @var myUser $sf_user */
/** @var sfPartialView $sf_view */
/** @var Agent $agent */
?>
<td>
  <ul class="sf_admin_td_actions">
    <li> <?php echo auth()->user()->can('edit', \App\Models\Project::find($agent->getId())) ?
          sf_link_to(image_tag('/jpAdminPlugin/images/edit_icon.png',
                               [ 'alt' => __s('edit'), 'title' => __s('edit') ]),
                     '@agent_edit?id=' . $agent->getId()) : '&nbsp;' ?></li>
  </ul>
</td>
