# rdf
uri_concept:
  url:  /:scheme/:concept.rdf
  param: { module: rdf, action: showConcept, type: uri }

uri_scheme:
  url:  /:scheme.rdf
  param: { module: rdf, action: showScheme, type: uri }

rdf_concept:
  url:  /concept/show/:id.rdf
  param: { module: rdf, action: showConcept, type: rdf }

rdf_vocabulary:
  url:  /vocabulary/show/:id.rdf
  param: { module: rdf, action: showScheme, type: rdf }

# user
user_profile:
  url:   /user/:nickname
  param: { module: user, action: show }

user_update:
  url:   /update_user
  param: { module: user, action: update }

current_user_profile:
  url:   /user
  param: { module: user, action: show }

add_account:
  url:   /add_user
  param: { module: user, action: add }

user_require_password:
  url:   /password_request
  param: { module: user, action: passwordRequest }

# login
login:
  url:   /login
  param: { module: user, action: login }

logout:
  url:   /logout
  param: { module: user, action: logout }

# content
about:
  url:   /about
  param: { module: content, action: about }

# default rules
homepage:
  url:   /
  param: { module: vocabulary, action: list }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*