loginSuccess:
  javascripts: [setfocus: { position: last }]

passwordRequestSuccess:
  javascripts: [setfocus: { position: last }]

showSuccess:
  javascripts: [setfocus: { position: last }]

showSubscriberSuccess:
  javascripts: [setfocus: { position: last }]

all:
  stylesheets: [-*, %SF_ADMIN_WEB_DIR%/main, main, layout]
  stylesheets: [user/layout]

  components:
    menubar:      []