all:
  is_secure:  off
  object_credentials:
    module:            vocabulary                 #object_credential array that holds the key to match against
    request_param:     vocabulary_id              #request paramter to pass to the key class::method or to lookup

edit:
  is_secure:   on
  credentials: [[administrator, vocabularymaintainer, vocabularyadmin, conceptpropadmin]]
