<?php
// auto-generated by sfPropelCrud
// date: 2007/02/03 15:47:09
?>
<table>
<tbody>
<tr>
<th>Vocabulary: </th>
<td><?php echo $vocabulary_has_user->getVocabularyId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $vocabulary_has_user->getUserId() ?></td>
</tr>
<tr>
<th>Is maintainer for: </th>
<td><?php echo $vocabulary_has_user->getIsMaintainerFor() ?></td>
</tr>
<tr>
<th>Is registrar for: </th>
<td><?php echo $vocabulary_has_user->getIsRegistrarFor() ?></td>
</tr>
<tr>
<th>Is admin for: </th>
<td><?php echo $vocabulary_has_user->getIsAdminFor() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'vocabuser/edit?vocabulary_id='.$vocabulary_has_user->getVocabularyId().'&user_id='.$vocabulary_has_user->getUserId()) ?>
&nbsp;<?php echo link_to('list', 'vocabuser/list') ?>
