all:
  is_secure:   off
  object_credentials:
    key:
      class:       schema_has_user    #object class that holds the key to match against
      method:      getSchemaId        #object method to use to retrieve property to pass to the key class::method or to lookup
    module:        schema             #object_credential array that holds the key to match against
    request_param: schema_id

create:
  is_secure:   on
  credentials: [[administrator, schemaadmin, schemauseradmin, agentadmin]]

edit:
  is_secure:   on
  credentials: [[administrator, schemaadmin, schemauseradmin, agentadmin]]
