prod:
  propel:
    param:
      host:               localhost
      username:
      password:

all:
  propel:
    class:                sfPropelDatabase
    param:
      phptype:            mysql
      host:               localhost
      database:           swregistry
      username:
      password:
      compat_assoc_lower: true
      # datasource:       propel

