prod:
  propel:
    param:
      database:           swregistry

dev:
  propel:
    param:
      database:           swregistry

sandbox:
  propel:
    param:
      database:           swregistry_test
all:
  propel:
    class:          sfPropelDatabase
    param:
#      dsn:          mysql://root:@localhost/dbname
      host:               localhost
      phptype:            mysql
      username:           root
      password:           RegIt!
      compat_assoc_lower: true
      datasource:         propel
