<?php return array (
  475 => 
  array (
    'reg_id' => '475',
    '*preferred label[0]_en' => 'audio',
    '*preferred label[0]_fr' => 'audio',
    'alternative label[0]_en' => '',
    'alternative label[0]_fr' => '',
    'ToolkitLabel_en' => 'audio',
    'ToolkitLabel_fr' => 'audio',
    'definition[0]_en' => 'A media type used to store recorded sound, designed for use with a playback device such as a turntable, audiocassette player, CD player, or MP3 player.',
    'definition[0]_fr' => 'Média servant à emmagasiner du son enregistré et conçu pour une utilisation au moyen d’un dispositif de lecture tel qu’une platine, un lecteur de cassette audio, un lecteur de CD ou un lecteur MP3.',
    'ToolkitDefinition_en' => 'A media type used to store recorded sound, designed for use with a playback device such as a turntable, audiocassette player, CD player, or MP3 player.',
    'ToolkitDefinition_fr' => '',
    'scope note[0]_en' => 'Media used to store digitally encoded as well as analog sound are included.',
    'scope note[1]_en' => '',
    'scope note[0]_fr' => 'Comprend tout média servant à emmagasiner du son encodé numériquement aussi bien que du son analogique.',
    'scope note[1]_fr' => '',
    '*uri' => 'RDAMediaType:1001',
    '*status' => 'Published',
  ),
  476 => 
  array (
    'reg_id' => '476',
    '*preferred label[0]_en' => 'microform',
    '*preferred label[0]_fr' => 'microforme',
    'alternative label[0]_en' => '',
    'alternative label[0]_fr' => '',
    'ToolkitLabel_en' => 'microform',
    'ToolkitLabel_fr' => 'microforme',
    'definition[0]_en' => 'A media type used to store reduced-size images not readable to the human eye, designed for use with a device such as a microfilm or microfiche reader.',
    'definition[0]_fr' => 'Média servant à emmagasiner des images de taille réduite non lisibles à l’œil nu, et conçu pour une utilisation au moyen d’un dispositif tel que : lecteur de microfilm ou de microfiche.',
    'ToolkitDefinition_en' => 'A media type used to store reduced-size images not readable to the human eye, designed for use with a device such as a microfilm or microfiche reader.',
    'ToolkitDefinition_fr' => '',
    'scope note[0]_en' => 'Both transparent and opaque micrographic media are included.',
    'scope note[1]_en' => '',
    'scope note[0]_fr' => 'Comprend les deux médias microphotographiques, transparent et opaque.',
    'scope note[1]_fr' => '',
    '*uri' => 'RDAMediaType:1002',
    '*status' => 'Published',
  ),
  477 => 
  array (
    'reg_id' => '477',
    '*preferred label[0]_en' => 'computer',
    '*preferred label[0]_fr' => 'informatique',
    'alternative label[0]_en' => '',
    'alternative label[0]_fr' => '',
    'ToolkitLabel_en' => 'computer',
    'ToolkitLabel_fr' => 'informatique',
    'definition[0]_en' => 'A media type used to store electronic files, designed for use with a computer.',
    'definition[0]_fr' => 'Média servant à emmagasiner des fichiers électroniques et conçu pour une utilisation au moyen d’un ordinateur.',
    'ToolkitDefinition_en' => 'A media type used to store electronic files, designed for use with a computer.',
    'ToolkitDefinition_fr' => '',
    'scope note[0]_en' => 'Media that are accessed remotely through file servers as well as direct-access media such as computer tapes and discs are included.',
    'scope note[1]_en' => '',
    'scope note[0]_fr' => 'Comprend tout média accessible à distance par serveur aussi bien que tout média en accès direct tel que des bandes et des disques informatiques.',
    'scope note[1]_fr' => '',
    '*uri' => 'RDAMediaType:1003',
    '*status' => 'Published',
  ),
  479 => 
  array (
    'reg_id' => '479',
    '*preferred label[0]_en' => 'projected',
    '*preferred label[0]_fr' => 'projeté',
    'alternative label[0]_en' => '',
    'alternative label[0]_fr' => '',
    'ToolkitLabel_en' => 'projected',
    'ToolkitLabel_fr' => 'projeté',
    'definition[0]_en' => 'A media type used to store moving or still images, designed for use with a projection device such as a motion picture film projector, slide projector, or overhead projector.',
    'definition[0]_fr' => 'Média servant à emmagasiner des images, animées ou fixes, et conçu pour une utilisation au moyen d’un dispositif de projection tel que : projecteur de film cinématographique, projecteur de diapositives ou rétroprojecteur.',
    'ToolkitDefinition_en' => 'A media type used to store moving or still images, designed for use with a projection device such as a motion picture film projector, slide projector, or overhead projector.',
    'ToolkitDefinition_fr' => '',
    'scope note[0]_en' => 'Media designed to project both two-dimensional and three-dimensional images are included.',
    'scope note[1]_en' => '',
    'scope note[0]_fr' => 'Comprend tout média conçu pour projeter des images bidimensionnelles et tridimensionnelles.',
    'scope note[1]_fr' => '',
    '*uri' => 'RDAMediaType:1005',
    '*status' => 'Published',
  ),
  480 => 
  array (
    'reg_id' => '480',
    '*preferred label[0]_en' => 'stereographic',
    '*preferred label[0]_fr' => 'stéréoscopique',
    'alternative label[0]_en' => '',
    'alternative label[0]_fr' => '',
    'ToolkitLabel_en' => 'stereographic',
    'ToolkitLabel_fr' => 'stéréoscopique',
    'definition[0]_en' => 'A media type used to store pairs of still images, designed for use with a device such as a stereoscope or stereograph viewer to give the effect of three dimensions.',
    'definition[0]_fr' => 'Média servant à emmagasiner des paires d’images fixes et conçu pour une utilisation au moyen d’un dispositif tel qu’un stéréoscope ou une visionneuse stéréoscopique pour donner l’impression des trois dimensions.',
    'ToolkitDefinition_en' => 'A media type used to store pairs of still images, designed for use with a device such as a stereoscope or stereograph viewer to give the effect of three dimensions.',
    'ToolkitDefinition_fr' => '',
    'scope note[0]_en' => '',
    'scope note[1]_en' => '',
    'scope note[0]_fr' => '',
    'scope note[1]_fr' => '',
    '*uri' => 'RDAMediaType:1006',
    '*status' => 'Published',
  ),
  481 => 
  array (
    'reg_id' => '481',
    '*preferred label[0]_en' => 'unmediated',
    '*preferred label[0]_fr' => 'sans médiation',
    'alternative label[0]_en' => '',
    'alternative label[0]_fr' => '',
    'ToolkitLabel_en' => 'unmediated',
    'ToolkitLabel_fr' => 'sans médiation',
    'definition[0]_en' => 'A media type used to store content designed to be perceived directly through one or more of the human senses without the aid of an intermediating device.',
    'definition[0]_fr' => 'Média servant à emmagasiner un contenu conçu pour être perçu directement par un ou plusieurs sens humains sans l’aide d’un dispositif de médiation.',
    'ToolkitDefinition_en' => 'A media type used to store content designed to be perceived directly through one or more of the human senses without the aid of an intermediating device.',
    'ToolkitDefinition_fr' => '',
    'scope note[0]_en' => 'Media containing visual and/or tactile content produced using processes such as printing, engraving, lithography, etc., embossing, texturing, etc., or by means of handwriting, drawing, painting, etc., are included. Media used to convey three-dimensional forms such as sculptures, models, etc., are also included.',
    'scope note[1]_en' => 'Also includes media used to convey three-dimensional forms such as sculptures, models, etc.',
    'scope note[0]_fr' => 'Comprend tout média à contenu visuel et/ou tactile produit selon des procédés tels que : impression, gravure, lithographie, etc. ; embossage, texturation, etc. ; ou bien encore au moyen de l’écriture à la main, du dessin, de la peinture, etc. Comprend également tout média servant à communiquer des formes tridimensionnelles telles que : sculptures, maquettes, etc.',
    'scope note[1]_fr' => '',
    '*uri' => 'RDAMediaType:1007',
    '*status' => 'Published',
  ),
  482 => 
  array (
    'reg_id' => '482',
    '*preferred label[0]_en' => 'video',
    '*preferred label[0]_fr' => 'vidéo',
    'alternative label[0]_en' => '',
    'alternative label[0]_fr' => '',
    'ToolkitLabel_en' => 'video',
    'ToolkitLabel_fr' => 'vidéo',
    'definition[0]_en' => 'A media type used to store moving or still images, designed for use with a playback device such as a videocassette player or DVD player.',
    'definition[0]_fr' => 'Média servant à emmagasiner des images animées ou fixes et conçu pour une utilisation au moyen d’un dispositif de lecture tel qu’un lecteur de cassette vidéo ou de DVD.',
    'ToolkitDefinition_en' => 'A media type used to store moving or still images, designed for use with a playback device such as a videocassette player or DVD player.',
    'ToolkitDefinition_fr' => '',
    'scope note[0]_en' => 'Media used to store digitally encoded as well as analog images are included.',
    'scope note[1]_en' => '',
    'scope note[0]_fr' => 'Comprend tout média servant à emmagasiner des images encodées numériquement aussi bien que des images analogiques.',
    'scope note[1]_fr' => '',
    '*uri' => 'RDAMediaType:1008',
    '*status' => 'Published',
  ),
);
