<?php return array (
  'id' => null,
  'created_at' => null,
  'updated_at' => null,
  'created_user_id' => 1,
  'action' => 'updated',
  'schema_property_element_id' => 107698,
  'schema_property_id' => 14328,
  'schema_id' => 83,
  'profile_property_id' => 2,
  'object' => 'angobango',
  'related_schema_property_id' => NULL,
  'language' => 'English',
  'status_id' => 1,
  'change_note' => NULL,
  'import_id' => 29,
  'created_by' => NULL,
);
