<?php return array (
  'id' => null,
  'created_at' => null,
  'updated_at' => null,
  'created_user_id' => 1,
  'action' => 'deleted',
  'schema_property_element_id' => 107698,
  'schema_property_id' => 14328,
  'schema_id' => 83,
  'profile_property_id' => 2,
  'object' => 'work',
  'related_schema_property_id' => null,
  'language' => 'en',
  'status_id' => 1,
  'change_note' => null,
  'import_id' => null,
  'created_by' => null,
);
