<?php return array (
  0 =>
  array (
    0 => 'reg_id',
    1 => '*preferred label[0]_en',
    2 => '*preferred label[0]_fr',
    3 => 'alternative label[0]_en',
    4 => 'alternative label[0]_fr',
    5 => 'ToolkitLabel_en',
    6 => 'ToolkitLabel_fr',
    7 => 'definition[0]_en',
    8 => 'definition[0]_fr',
    9 => 'ToolkitDefinition_en',
    10 => 'ToolkitDefinition_fr',
    11 => 'scope note[0]_en',
    12 => 'scope note[1]_en',
    13 => 'scope note[0]_fr',
    14 => 'scope note[1]_fr',
    15 => '*uri',
    16 => '*status',
  ),
  1 =>
  array (
    0 => '475',
    1 => 'audio',
    2 => 'audio',
    3 => '',
    4 => '',
    5 => 'audio',
    6 => 'audio',
    7 => 'A media type used to store recorded sound, designed for use with a playback device such as a turntable, audiocassette player, CD player, or MP3 player.',
    8 => 'Média servant à emmagasiner du son enregistré et conçu pour une utilisation au moyen d’un dispositif de lecture tel qu’une platine, un lecteur de cassette audio, un lecteur de CD ou un lecteur MP3.',
    9 => 'A media type used to store recorded sound, designed for use with a playback device such as a turntable, audiocassette player, CD player, or MP3 player.',
    10 => '',
    11 => 'Media used to store digitally encoded as well as analog sound are included.',
    12 => '',
    13 => 'Comprend tout média servant à emmagasiner du son encodé numériquement aussi bien que du son analogique.',
    14 => '',
    15 => 'RDAMediaType:1001',
    16 => 'Published',
  ),
  2 =>
  array (
    0 => '476',
    1 => 'microform',
    2 => 'microforme',
    3 => '',
    4 => '',
    5 => 'microform',
    6 => 'microforme',
    7 => 'A media type used to store reduced-size images not readable to the human eye, designed for use with a device such as a microfilm or microfiche reader.',
    8 => 'Média servant à emmagasiner des images de taille réduite non lisibles à l’œil nu, et conçu pour une utilisation au moyen d’un dispositif tel que : lecteur de microfilm ou de microfiche.',
    9 => 'A media type used to store reduced-size images not readable to the human eye, designed for use with a device such as a microfilm or microfiche reader.',
    10 => '',
    11 => 'Both transparent and opaque micrographic media are included.',
    12 => '',
    13 => 'Comprend les deux médias microphotographiques, transparent et opaque.',
    14 => '',
    15 => 'RDAMediaType:1002',
    16 => 'Published',
  ),
  3 =>
  array (
    0 => '477',
    1 => 'computer',
    2 => 'informatique',
    3 => '',
    4 => '',
    5 => 'computer',
    6 => 'informatique',
    7 => 'A media type used to store electronic files, designed for use with a computer.',
    8 => 'Média servant à emmagasiner des fichiers électroniques et conçu pour une utilisation au moyen d’un ordinateur.',
    9 => 'A media type used to store electronic files, designed for use with a computer.',
    10 => '',
    11 => 'Media that are accessed remotely through file servers as well as direct-access media such as computer tapes and discs are included.',
    12 => '',
    13 => 'Comprend tout média accessible à distance par serveur aussi bien que tout média en accès direct tel que des bandes et des disques informatiques.',
    14 => '',
    15 => 'RDAMediaType:1003',
    16 => 'Published',
  ),
  4 =>
  array (
    0 => '478',
    1 => 'microscopic',
    2 => 'microscopique',
    3 => '',
    4 => '',
    5 => 'microscopic',
    6 => 'microscopique',
    7 => 'A media type used to store minute objects, designed for use with a device such as a microscope to reveal details invisible to the naked eye.',
    8 => 'Média servant à emmagasiner des objets minuscules et conçu pour une utilisation au moyen d’un dispositif tel qu’un microscope, pour faire apparaître des détails invisibles à l’œil nu.',
    9 => 'A media type used to store minute objects, designed for use with a device such as a microscope to reveal details invisible to the naked eye.',
    10 => '',
    11 => '',
    12 => '',
    13 => '',
    14 => '',
    15 => 'RDAMediaType:1004',
    16 => 'Published',
  ),
  5 =>
  array (
    0 => '479',
    1 => 'projected',
    2 => 'projeté',
    3 => '',
    4 => '',
    5 => 'projected',
    6 => 'projeté',
    7 => 'A media type used to store moving or still images, designed for use with a projection device such as a motion picture film projector, slide projector, or overhead projector.',
    8 => 'Média servant à emmagasiner des images, animées ou fixes, et conçu pour une utilisation au moyen d’un dispositif de projection tel que : projecteur de film cinématographique, projecteur de diapositives ou rétroprojecteur.',
    9 => 'A media type used to store moving or still images, designed for use with a projection device such as a motion picture film projector, slide projector, or overhead projector.',
    10 => '',
    11 => 'Media designed to project both two-dimensional and three-dimensional images are included.',
    12 => '',
    13 => 'Comprend tout média conçu pour projeter des images bidimensionnelles et tridimensionnelles.',
    14 => '',
    15 => 'RDAMediaType:1005',
    16 => 'Published',
  ),
  6 =>
  array (
    0 => '480',
    1 => 'stereographic',
    2 => 'stéréoscopique',
    3 => '',
    4 => '',
    5 => 'stereographic',
    6 => 'stéréoscopique',
    7 => 'A media type used to store pairs of still images, designed for use with a device such as a stereoscope or stereograph viewer to give the effect of three dimensions.',
    8 => 'Média servant à emmagasiner des paires d’images fixes et conçu pour une utilisation au moyen d’un dispositif tel qu’un stéréoscope ou une visionneuse stéréoscopique pour donner l’impression des trois dimensions.',
    9 => 'A media type used to store pairs of still images, designed for use with a device such as a stereoscope or stereograph viewer to give the effect of three dimensions.',
    10 => '',
    11 => '',
    12 => '',
    13 => '',
    14 => '',
    15 => 'RDAMediaType:1006',
    16 => 'Published',
  ),
  7 =>
  array (
    0 => '481',
    1 => 'unmediated',
    2 => 'sans médiation',
    3 => '',
    4 => '',
    5 => 'unmediated',
    6 => 'sans médiation',
    7 => 'A media type used to store content designed to be perceived directly through one or more of the human senses without the aid of an intermediating device.',
    8 => 'Média servant à emmagasiner un contenu conçu pour être perçu directement par un ou plusieurs sens humains sans l’aide d’un dispositif de médiation.',
    9 => 'A media type used to store content designed to be perceived directly through one or more of the human senses without the aid of an intermediating device.',
    10 => '',
    11 => 'Media containing visual and/or tactile content produced using processes such as printing, engraving, lithography, etc., embossing, texturing, etc., or by means of handwriting, drawing, painting, etc., are included. Media used to convey three-dimensional forms such as sculptures, models, etc., are also included.',
    12 => 'Also includes media used to convey three-dimensional forms such as sculptures, models, etc.',
    13 => 'Comprend tout média à contenu visuel et/ou tactile produit selon des procédés tels que : impression, gravure, lithographie, etc. ; embossage, texturation, etc. ; ou bien encore au moyen de l’écriture à la main, du dessin, de la peinture, etc. Comprend également tout média servant à communiquer des formes tridimensionnelles telles que : sculptures, maquettes, etc.',
    14 => '',
    15 => 'RDAMediaType:1007',
    16 => 'Published',
  ),
  8 =>
  array (
    0 => '482',
    1 => 'video',
    2 => 'vidéo',
    3 => '',
    4 => '',
    5 => 'video',
    6 => 'vidéo',
    7 => 'A media type used to store moving or still images, designed for use with a playback device such as a videocassette player or DVD player.',
    8 => 'Média servant à emmagasiner des images animées ou fixes et conçu pour une utilisation au moyen d’un dispositif de lecture tel qu’un lecteur de cassette vidéo ou de DVD.',
    9 => 'A media type used to store moving or still images, designed for use with a playback device such as a videocassette player or DVD player.',
    10 => '',
    11 => 'Media used to store digitally encoded as well as analog images are included.',
    12 => '',
    13 => 'Comprend tout média servant à emmagasiner des images encodées numériquement aussi bien que des images analogiques.',
    14 => '',
    15 => 'RDAMediaType:1008',
    16 => 'Published',
  ),
  9 =>
  array (
    0 => '',
    1 => 'foobar',
    2 => 'fubaire',
    3 => '',
    4 => '',
    5 => 'foobar',
    6 => 'fubaire',
    7 => 'English definition',
    8 => 'French definition',
    9 => 'English Toolkit Definition',
    10 => 'French Toolkit definition',
    11 => 'First English Scope Note',
    12 => 'Second English Scope Note',
    13 => 'First French Scope Note',
    14 => 'Second French Scope Note',
    15 => 'RDAMediaType:1009',
    16 => 'Published',
  ),
);
