<?php return array (
  'id' => NULL,
  'created_at' => NULL,
  'updated_at' => NULL,
  'action' => 'updated',
  'concept_property_id' => 1281,
  'concept_id' => 475,
  'vocabulary_id' => 37,
  'skos_property_id' => NULL,
  'object' => 'audio',
  'scheme_id' => NULL,
  'related_concept_id' => NULL,
  'language' => 'English',
  'status_id' => 1,
  'created_user_id' => 1,
  'change_note' => NULL,
  'import_id' => NULL,
  'profile_property_id' => 45,
  'created_by' => NULL,
);
