generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      AgentHasUser
    theme:            default

    list:
      peer_method:     doSelectJoinAll
      title:           Members of %%agent%%
      fields:
        agent:         { name: Owner }
      display:         [_user, _agent, isRegistrarFor, isAdminFor]
      object_actions:
        _edit:         { credentials: [[administrator, agentadmin]] }
        _delete:       { credentials: [[administrator, agentadmin]] }
      actions:
        _create:       { name: Add Member, credentials: [[administrator, agentadmin]] }
      displayfilter:   false
      filters:         [agent_id, user_id]
      urlfilters:
        agent_id:      agent_id
        user_id:       user_id
