<?php
// auto-generated by sfPropelCrud
// date: 2007/02/03 15:45:25
?>
<?php use_helper('Object') ?>

<?php echo form_tag('conceptprop/update') ?>

<?php echo object_input_hidden_tag($concept_property, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Last updated:</th>
  <td><?php echo object_input_date_tag($concept_property, 'getLastUpdated', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Concept*:</th>
  <td><?php echo object_select_tag($concept_property, 'getConceptId', array (
  'related_class' => 'Concept',
)) ?></td>
</tr>
<tr>
  <th>Skos property*:</th>
  <td><?php echo object_select_tag($concept_property, 'getSkosPropertyId', array (
  'related_class' => 'SkosProperty',
)) ?></td>
</tr>
<tr>
  <th>Object*:</th>
  <td><?php echo object_textarea_tag($concept_property, 'getObject', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Scheme:</th>
  <td><?php echo object_select_tag($concept_property, 'getSchemeId', array (
  'related_class' => 'Vocabulary',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Related concept:</th>
  <td><?php echo object_select_tag($concept_property, 'getRelatedConceptId', array (
  'related_class' => 'Concept',
  'include_blank' => true,
)) ?></td>
</tr>
<tr>
  <th>Language:</th>
  <td><?php echo object_input_tag($concept_property, 'getLanguage', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Status:</th>
  <td><?php echo object_select_tag($concept_property, 'getStatusId', array (
  'related_class' => 'Lookup',
  'include_blank' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($concept_property->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'conceptprop/delete?id='.$concept_property->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'conceptprop/show?id='.$concept_property->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'conceptprop/list') ?>
<?php endif; ?>
</form>
