<?php
// auto-generated by sfPropelCrud
// date: 2007/02/03 15:45:25
?>
<h1>conceptprop</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Created at</th>
  <th>Last updated</th>
  <th>Concept</th>
  <th>Skos property</th>
  <th>Object</th>
  <th>Scheme</th>
  <th>Related concept</th>
  <th>Language</th>
  <th>Status</th>
</tr>
</thead>
<tbody>
<?php foreach ($concept_propertys as $concept_property): ?>
<tr>
    <td><?php echo link_to($concept_property->getId(), 'conceptprop/show?id='.$concept_property->getId()) ?></td>
      <td><?php echo $concept_property->getCreatedAt() ?></td>
      <td><?php echo $concept_property->getLastUpdated() ?></td>
      <td><?php echo $concept_property->getConceptId() ?></td>
      <td><?php echo $concept_property->getSkosPropertyId() ?></td>
      <td><?php echo $concept_property->getObject() ?></td>
      <td><?php echo $concept_property->getSchemeId() ?></td>
      <td><?php echo $concept_property->getRelatedConceptId() ?></td>
      <td><?php echo $concept_property->getLanguage() ?></td>
      <td><?php echo $concept_property->getStatusId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'conceptprop/create') ?>
