generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Concept
    theme:            default

    fields:
      id:             { name: ID }
      uri:            { name: URI }
      created_at:
        name: Date Created
        type: plain
        params: date_format='MM/dd/yy'
      last_updated:
        name: Last Updated
        help: This is the date the Concept was last updated
        type: plain
        params: date_format='MM/dd/yy'
      pref_label:     { name: Label }
      vocabulary:     { name: Vocabulary }
      vocabulary_id:  { name: Vocabulary }
      is_top_concept: { name: Top Concept? }
      _versions:      { name: History }
      _properties:    { name: Properties }
      _listproperties: { name: Properties }

    list:
      title:          Concepts for %%vocabulary%%
      fields:
        is_top_concept: { name: " ", help: This is a top-level concept  }
      display:        [is_top_concept, =prefLabel, last_updated]
      displayfilter:  false
      actions:
        _create:        { credentials: [[administrator, vocabularymaintainer]] }
      filters:          [is_top_concept, vocabulary_id, pref_label, last_updated, is_top_concept]
      urlfilters:
        vocabulary_id: vocabulary_id

    edit:
      title:        Detail for %%pref_label%%
      display:      [vocabulary_id, pref_label, uri, is_top_concept]
      fields:
        id:           { type: plain }
        created_at:   { type: plain }
        last_updated: { type: plain }
      actions:
        _list:
          query_string:
            vocabulary_id: vocabulary_id
        _save:         { credentials: [[administrator, vocabularymaintainer]] }
        _delete:       { credentials: [administrator] }
        _create:       { credentials: [[administrator, vocabularymaintainer]] }
        _save_and_add: { credentials: [[administrator, vocabularymaintainer]] }

    create:
      fields:
        vocabulary_id:  { type: input_hidden_tag }
      display:          [vocabulary_id, pref_label, uri, is_top_concept]

    show:
      fields:
        id:            { name: ID, credentials: [administrator] }
        uri:           { helper: auto_link_text }
      _listproperties: { name: Properties }
      display:        [vocabulary, id, created_at, last_updated, pref_label, uri, is_top_concept, _listproperties]
      actions:
        _edit:        { credentials: [[administrator, vocabularymaintainer]] }
        _list:
          query_string:
            vocabulary_id: vocabulary_id
        rdf:            { name: Get RDF, icon: /sf/sf_admin/images/rdf_icon.png }
            
