generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Concept
    theme:            default

    fields:
      id:
         name:        ID
         type:        plain
      created_at:
        name:         Date Created
        type:         plain
        params:       date_format='MM/dd/yy'
      last_updated:
        name:         Last Updated
        help:         This is the date the Concept was last updated
        type:         plain
        params:       date_format='MM/dd/yy'
      uri:            { name: URI }
      pref_label:     { name: Label }
      vocabulary:     { name: Vocabulary }
      vocabulary_id:  { name: Vocabulary }
      status_id:      { name: Status }
      is_top_concept: { name: Top Concept? }
      versions:       { name: History }
      properties:     { name: Properties }
      listproperties: { name: " " }

    list:
      title:            Concepts for %%vocabulary%%
      fields:
        is_top_concept: { name: " ", help: This is a top-level concept  }
      display:          [is_top_concept, =prefLabel, uri, status, last_updated]
      displayfilter:    false
      object_actions:
        _edit:          { credentials: [[administrator, vocabularymaintainer, vocabularyadmin]] }
      actions:
        _create:        { name: Add Concept, credentials: [[administrator, vocabularymaintainer, vocabularyadmin]] }
      filters:          [vocabulary_id, pref_label, last_updated, is_top_concept, status]
      urlfilters:
        vocabulary_id:  vocabulary_id

    edit:
      fields:
        id:            { credentials: [administrator], mode: edit }
      title:           Detail for %%pref_label%%
      hide:            [vocabulary_id]
      display:
        "-Metadata":   { fields: [id, created_at, last_updated], mode: edit, credentials: [[administrator, vocabularymaintainer, vocabularyadmin]] }
        "Detail":      [pref_label, uri, is_top_concept, status_id]
        "Properties":  [_listproperties]
      actions:
        _list:         { query_string: { vocabulary_id: vocabulary_id} }
        _save:         { credentials: [[administrator, vocabularymaintainer, vocabularyadmin]] }
        _delete:       { credentials: [[administrator, vocabularyadmin]] }
        _create:       { name: Add Concept, credentials: [[administrator, vocabularymaintainer, vocabularyadmin]], mode: edit  }
        _save_and_add: { credentials: [[administrator, vocabularymaintainer, vocabularyadmin]] }

    show:
      fields:
        id:            { credentials: [administrator] }
        uri:           { helper: auto_link_text }
      display:
        "-Metadata":   { fields: [id, created_at, last_updated], credentials: [[administrator, vocabularymaintainer, vocabularyadmin]] }
        "Detail":      [pref_label, uri, is_top_concept, status]
        "Properties":  [_listproperties]
      actions:
        _edit:         { credentials: [[administrator, vocabularymaintainer]] }
        _create:       { name: Add Concept, credentials: [[administrator, vocabularymaintainer]] }
        _list:         { query_string: { vocabulary_id: vocabulary_id} }
        rdf:           { name: Get RDF, icon: %SF_ADMIN_WEB_DIR%/images/rdf_icon.png, route: rdf_concept }
            
