generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Schema
    theme:            default
    fields:
      id:             { name: ID, type: plain}
      created_at:     { name: Date Created, type: plain, params: date_format='s', help: This is the date the schema was created }
      updated_at:     { name: Last Updated, type: plain, params: date_format='s', help: This is the date the schema was last updated }
      agent:          { name: Owner, help: The individual or organization that registered the schema }
      agent_id:       { name: Owner, help: The individual or organization that registered the schema }
      created_user:   { name: Created by, type: plain, help: The user who created this schema}
      updated_user:   { name: Updated by, type: plain, help: The user who last updated this schema}
      name:           { name: Label, help: A human-readable descriptive label for the schema. This will be displayed in lists of schema. }
      note:           { name: Note, help: A note about this schema }
      url:            { name: URL, help: A non-Registry URL that contains more information about this schema }
      base_domain:    { name: Base Domain, help: The root of all URIs for this schema and its terms. Defaults to the Base Domain set by the Owner of this schema. }
      token:          { name: Name, help: A unique token representing this schema. This can be used as the the short form of this URI in RDF or a qname in XML}
      uri:            { name: URI, help: The Namespace URI of this schema. By default this will be a concatenation of the Base Domain and the Token. }
      community:      { name: Tags, help: Tags identifying communities of practice that this schema addresses }
      language:       { name: Language, help: Default language for the properties of this schema }
      status_id:      { name: Status, help: Default status for the properties of this schema }

    list:
      title:          Schema
      fields:
        updated_at:   { params: date_format='yyyy-MM-dd' }
      display:        [=name, _agent, updated_at, updated_user]
      sort:           name
      object_actions:
        _edit:        { credentials: [[administrator, schemamaintainer, schemaadmin]] }
      actions:
        _create:      { name: Add schema,  credentials: [[administrator, hasAgents]] }
      filters:
#        agent_id:     { name: agent_id, params: peer_method=getSchemaAgents related_class=Schema }
        agent_id:     agent_id

    edit:
      title:
        mode:
          edit:       Editing %%name%%
          create:     Creating new schema
      helptype:       icon
      fields:
        id:           { credentials: [administrator], mode: edit }
        agent_id:     { params: peer_method=getAgentsForCurrentUser}
        token:        { params: onblur=updateUri() }
        language:     { type: select_language_tag }
      hide:           [base_domain]
      display:
        "-Metadata":  { fields: [id, created_at, created_user, updated_at, updated_user], mode: edit }
        "Detail":     [agent_id, name]
        "Namespace":  [token, uri]
        "Documentation": [url, note, community]
        "Defaults":   [status_id, language]
      actions:
        _list:         -
        _save:         { credentials: [[administrator, hasAgents, schemamaintainer, schemaadmin]] }
        _delete:       { credentials: [administrator] }
        _create:       { credentials: [[administrator, hasAgents]], mode: edit }
        _save_and_add: { credentials: [administrator] }
        _cancel:       { credentials: [[administrator, hasAgents, schemamaintainer, schemaadmin]] }

    show:
      title:           Show detail for %%name%%
      fields:
        id:            { credentials: [administrator] }
        uri:           { helper: auto_link_text }
        url:           { helper: auto_link_text }
        created_at:    { params: date_format='F' }
        updated_at:    { params: date_format='F' }
        list_users:    { name: - }
      display:
        "-Metadata":   { fields: [id, created_at, created_user, updated_at, updated_user], credentials: [[administrator, schemamaintainer, schemaadmin]] }
        "Detail":      [_agent, name]
        "Namespace":   [token, uri]
        "Documentation": [url, note, community]
        "Defaults":    [status, _language]
        "-Users":      [_list_users]
      actions:
        _list:
        _edit:       { credentials: [[administrator, schemamaintainer, schemaadmin]] }
        showRdf:
          name:      Get RDF
          icon:      %SF_ADMIN_WEB_DIR%/images/rdf_icon.png
          route:     uri_schema_rdf
