---
propel:
  agent:
    ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
    AgentName:
      type: VARCHAR
      size: 255
      required: true
      default:
    _uniques:
      Agent_AK1:
        - AgentName
      Agent_AK1_uc4:
        - AgentName

  agent_user:
    User_ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
      foreignTable: user
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    Agent_ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
      foreignTable: agent
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    isAdminFor:
      type:
    _indexes:
      User_Agent_User_FK1:
        - User_ID

  concept:
    ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
    Isidentifiedby_conceptURI:
      type: VARCHAR
      size: 255
    UriTimeStamp:
      type: INTEGER
    Status_ID:
      type: INTEGER
      required: true
      default:
      foreignTable: status
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    Isidentifiedby_ConceptURI:
      type: VARCHAR
      size: 255
    _indexes:
      Status_concept_FK1:
        - Status_ID
    _uniques:
      concept_AK1:
        - Isidentifiedby_conceptURI
      concept_AK1_uc9:
        - Isidentifiedby_conceptURI
      concept_AK2:
        - UriTimeStamp
      concept_AK2_uc10:
        - UriTimeStamp
      concept_AK3:
        - Isidentifiedby_ConceptURI
      concept_AK3_uc11:
        - Isidentifiedby_ConceptURI

  concept_property:
    concept_ID:
      type: TINYINT
      required: true
      primaryKey: true
      default:
    property_ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
      foreignTable: property
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    _indexes:
      property_concept_property_FK1:
        - property_ID

  concept_vocabulary:
    concept_ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
      foreignTable: concept
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    vocabulary_ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
      foreignTable: vocabulary
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    _indexes:
      vocabulary_concept_vocabulary_FK1:
        - vocabulary_ID

  conceptversion:
    ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
    Versions_concept_ID:
      type: INTEGER
      required: true
      default:
      foreignTable: concept
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    Isidentifiedby_VersionURI:
      type: VARCHAR
      size: 255
    Date:
      type: TIMESTAMP
    VersionLabel:
      type: CHAR
      size: 255
    Createdby_User_ID:
      type: INTEGER
      required: true
      default:
      foreignTable: user
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    _indexes:
      concept_ConceptVersion_FK1:
        - Versions_concept_ID
      User_ConceptVersion_FK1:
        - Createdby_User_ID
    _uniques:
      ConceptVersion_AK1:
        - Isidentifiedby_VersionURI
      ConceptVersion_AK1_uc5:
        - Isidentifiedby_VersionURI
      ConceptVersion_AK2:
        - Date
      ConceptVersion_AK2_uc6:
        - Date
      ConceptVersion_AK3:
        - VersionLabel
      ConceptVersion_AK3_uc7:
        - VersionLabel

  property:
    ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
    SkosType:
      type: CHAR
      size: 255
      required: true
      default:
    Has_Value:
      type: LONGVARCHAR
    Createdby_User_ID:
      type: INTEGER
      required: true
      default:
      foreignTable: user
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    Status_ID:
      type: INTEGER
      required: true
      default:
      foreignTable: status
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    User_updated_ID:
      type: INTEGER
      required: true
      default:
      foreignTable: user
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    _indexes:
      Status_property_FK1:
        - Status_ID
      User_property_FK1:
        - Createdby_User_ID
      User_property_FK2:
        - User_updated_ID

  status:
    ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
    StatusName:
      type: VARCHAR
      size: 255
      required: true
      default:
    _uniques:
      Status_AK1:
        - StatusName
      Status_AK1_uc1:
        - StatusName

  user:
    ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
    UserName:
      type: CHAR
      size: 255
      required: true
      default:
    _uniques:
      User_AK1:
        - UserName
      User_AK1_uc2:
        - UserName

  vocabulary:
    ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
    Isidentifiedby_SchemeURI:
      type: VARCHAR
      size: 255
    ConceptVersion_versions_ID:
      type: INTEGER
      required: true
      default:
      foreignTable: conceptversion
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    Isownedby_Agent_ID:
      type: INTEGER
      required: true
      default:
      foreignTable: agent
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    _indexes:
      ConceptVersion_vocabulary_FK1:
        - ConceptVersion_versions_ID
      Agent_vocabulary_FK1:
        - Isownedby_Agent_ID
    _uniques:
      vocabulary_AK1:
        - Isidentifiedby_SchemeURI
      vocabulary_AK1_uc8:
        - Isidentifiedby_SchemeURI

  vocabulary_user:
    vocabulary_ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
      foreignTable: vocabulary
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    User_ID:
      type: INTEGER
      required: true
      primaryKey: true
      default:
      foreignTable: user
      foreignReference: ID
      onDelete: RESTRICT
      onUpdate: RESTRICT
    isAdminFor:
      type:
    isMaintainerFor:
      type:
    _indexes:
      User_vocabulary_User_FK1:
        - User_ID

