<?php
// auto-generated by sfPropelCrud
// date: 2007/02/03 15:43:22
?>
<?php use_helper('Object') ?>

<?php echo form_tag('user/update') ?>

<?php echo object_input_hidden_tag($user, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Last updated:</th>
  <td><?php echo object_input_date_tag($user, 'getLastUpdated', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Nickname:</th>
  <td><?php echo object_input_tag($user, 'getNickname', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
  <th>Salutation:</th>
  <td><?php echo object_input_tag($user, 'getSalutation', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>First name:</th>
  <td><?php echo object_input_tag($user, 'getFirstName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Last name:</th>
  <td><?php echo object_input_tag($user, 'getLastName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Email:</th>
  <td><?php echo object_input_tag($user, 'getEmail', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Sha1 password:</th>
  <td><?php echo object_input_tag($user, 'getSha1Password', array (
  'size' => 40,
)) ?></td>
</tr>
<tr>
  <th>Salt:</th>
  <td><?php echo object_input_tag($user, 'getSalt', array (
  'size' => 32,
)) ?></td>
</tr>
<tr>
  <th>Want to be moderator:</th>
  <td><?php echo object_checkbox_tag($user, 'getWantToBeModerator', array (
)) ?></td>
</tr>
<tr>
  <th>Is moderator:</th>
  <td><?php echo object_checkbox_tag($user, 'getIsModerator', array (
)) ?></td>
</tr>
<tr>
  <th>Is administrator:</th>
  <td><?php echo object_checkbox_tag($user, 'getIsAdministrator', array (
)) ?></td>
</tr>
<tr>
  <th>Deletions:</th>
  <td><?php echo object_input_tag($user, 'getDeletions', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Password:</th>
  <td><?php echo object_input_tag($user, 'getPassword', array (
  'size' => 40,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($user->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'user/delete?id='.$user->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'user/show?id='.$user->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'user/list') ?>
<?php endif; ?>
</form>
