<?php
// auto-generated by sfPropelAdmin
// date: 2016/03/11 21:12:40
?>
<?php if ( ! $sf_request->getParameter('agent_id') ):
use_helper('Object'); ?>
<div class="sf_admin_filters">
    <?php echo form_tag('vocabulary/list', [ 'method' => 'get' ]) ?>

    <fieldset>
        <h2><?php echo __('Filters') ?></h2>
        <div class="form-row">
            <label for="filters_agent_id"><?php echo __('Project:') ?></label>
            <div class="content">
                <?php echo object_select_tag(isset( $filters['agent_id'] ) ? $filters['agent_id'] : null,
                                             null,
                                             [
                                                 'include_blank' => true,
                                                 'related_class' => 'Vocabulary',
                                                 'peer_method'   => 'getVocabularyAgents',
                                                 'text_method'   => '__toString',
                                                 'control_name'  => 'agent_id',
                                                 'onchange' => "window.location.href = 'projects/' + this.value + '/vocabularies';"
                                             ]) ?>
            </div>
        </div>
    </fieldset>

    <ul class="sf_admin_actions">
        <li><?php echo button_to(__('Show All'), 'vocabulary/list', 'class=sf_admin_action_reset_filter') ?></li>
    </ul>

    </form>
</div>
<?php endif; ?>
