<?php
// auto-generated by sfPropelAdmin
// date: 2016/05/19 18:32:25
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'Text') ?>

<div id="sf_admin_container">
<div id="sf_admin_header">
<?php include_partial('vocabulary/show_header', array('vocabulary' => $vocabulary)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('vocabulary/show_messages', array('vocabulary' => $vocabulary, 'labels' => $labels)) ?>
<?php include_partial('vocabulary/show', array('vocabulary' => $vocabulary, 'labels' => $labels)) ?>


</div>

<div id="sf_admin_footer">
<?php include_partial('vocabulary/show_footer', array('vocabulary' => $vocabulary)) ?>
</div>
</div>